// AUTO-GENERATED by tools/gen_golden_params.py from config/rails/atm.json — DO NOT EDIT.
#pragma once
namespace seads { namespace golden {
constexpr double R_M        = 0x1.d4c0000000000p+13;
constexpr double DT_S       = 0x1.47ae147ae147bp-7;
constexpr double G0         = 0x1.39d013a92a305p+3;
constexpr double ATM_TOP_M  = 0x1.f400000000000p+12;
constexpr double SOFT_M     = 0x1.9000000000000p+6;
constexpr unsigned TICKS    = 10000u;
constexpr double START_LAT_DEG = 0x0.0p+0;
constexpr double START_LON_DEG = 0x0.0p+0;
constexpr double START_PSI_DEG = 0x1.6800000000000p+5;
constexpr double START_PHI_DEG = 0x0.0p+0;
constexpr double START_ALT_M   = 0x1.f400000000000p+9;
constexpr double START_TAS_MPS = 0x1.f400000000000p+7;
}} // namespace seads::golden
