// AUTO-GENERATED by tools/gen_scenario_params.py from config/scenarios/ — DO NOT EDIT.
// Scripted-timeline inputs (hex-float radians / u32 ticks) bit-identical to ref_kernel.py.
#pragma once
#include "envelope_tables.h"
namespace seads { namespace scen {
struct Phase  { unsigned start_tick; double target_phi; double target_climb; };
struct AcSpec { double lat, lon, psi, phi, alt, tas;
                const Envelope* env; const Phase* sched; unsigned n_phase; };
struct Scenario { const char* id; unsigned ticks; const AcSpec* ac; unsigned n_ac; };
constexpr Phase GOLDEN_SK_CLIMB_001_AC0_SCHED[] = {
  {0u, 0x0.0p+0, 0x0.0p+0},
  {100u, 0x0.0p+0, 0x1.8000000000000p+3},
  {3000u, 0x0.0p+0, 0x1.8000000000000p+3}
};
constexpr AcSpec GOLDEN_SK_CLIMB_001_AC[] = {
  { 0x0.0p+0, 0x0.0p+0, 0x1.921fb54442d18p+0, 0x0.0p+0, 0x1.e780000000000p+12, 0x1.4000000000000p+6, &envtab::BF109F4, GOLDEN_SK_CLIMB_001_AC0_SCHED, 3u }
};
constexpr Scenario GOLDEN_SK_CLIMB_001 = { "GOLDEN-SK-Climb-001", 3000u, GOLDEN_SK_CLIMB_001_AC, 1u };
constexpr Phase GOLDEN_SK_TURN_001_AC0_SCHED[] = {
  {0u, 0x0.0p+0, 0x0.0p+0},
  {200u, 0x1.921fb54442d18p-1, 0x0.0p+0},
  {6000u, 0x1.921fb54442d18p-1, 0x0.0p+0}
};
constexpr AcSpec GOLDEN_SK_TURN_001_AC[] = {
  { 0x0.0p+0, 0x0.0p+0, 0x1.921fb54442d18p-1, 0x0.0p+0, 0x1.f400000000000p+9, 0x1.1800000000000p+7, &envtab::KI61, GOLDEN_SK_TURN_001_AC0_SCHED, 3u }
};
constexpr Scenario GOLDEN_SK_TURN_001 = { "GOLDEN-SK-Turn-001", 6000u, GOLDEN_SK_TURN_001_AC, 1u };
constexpr Phase GOLDEN_SK_TURNCLIMB_001_AC0_SCHED[] = {
  {0u, 0x0.0p+0, 0x0.0p+0},
  {150u, 0x1.921fb54442d18p-1, 0x0.0p+0},
  {800u, 0x1.921fb54442d18p-1, 0x1.0000000000000p+3},
  {4000u, 0x1.921fb54442d18p-1, 0x1.0000000000000p+3}
};
constexpr AcSpec GOLDEN_SK_TURNCLIMB_001_AC[] = {
  { 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x1.7700000000000p+11, 0x1.e000000000000p+6, &envtab::SPITFIRE_MK5, GOLDEN_SK_TURNCLIMB_001_AC0_SCHED, 4u }
};
constexpr Scenario GOLDEN_SK_TURNCLIMB_001 = { "GOLDEN-SK-TurnClimb-001", 4000u, GOLDEN_SK_TURNCLIMB_001_AC, 1u };
constexpr const Scenario* ALL[] = {
    &GOLDEN_SK_CLIMB_001, &GOLDEN_SK_TURN_001, &GOLDEN_SK_TURNCLIMB_001
};
constexpr unsigned N_ALL = 3u;
}} // namespace seads::scen
