// AUTO-GENERATED by tools/gen_event_vectors.py — DO NOT EDIT.
// Reliable combat-EVENT channel (netcode layer 6) parity vectors: C++ harness vs
// tools/event_ref.py. Reuses the SESSION-SK-001 scenario (sess_vec::SCENARIO). Expected
// server event log + full-reconstruction digest + the kill + a K-consecutive-blackout
// reliability-bound vector + transport accounting.
#pragma once
#include <cstdint>
#include "event.h"            // seads::event::{Event, EVENT_WINDOW_K}
#include "session_vectors.h"  // reuse sess_vec::SCENARIO (SESSION-SK-001)
namespace seads { namespace event_vec {

constexpr int WINDOW_K = 4;   // must equal seads::event::EVENT_WINDOW_K

// --- server-derived authoritative event log (seq, tick, target, damage_milli, hp_after_milli, killed, attacker) ---
struct ExpectEvent { std::int64_t seq, tick, target, damage_milli, hp_after_milli, killed, attacker; };
constexpr ExpectEvent EXPECTED_EVENTS[] = {
  { 0, 40, 1, 12000, 58000, 0, 0 },
  { 1, 42, 1, 12000, 46000, 0, 0 },
  { 2, 45, 1, 12000, 34000, 0, 0 },
  { 3, 48, 1, 12000, 22000, 0, 0 },
  { 4, 51, 1, 12000, 10000, 0, 0 },
  { 5, 54, 1, 10000, 0, 1, 0 },
};
constexpr int EXPECTED_EVENT_COUNT = sizeof(EXPECTED_EVENTS)/sizeof(EXPECTED_EVENTS[0]);
constexpr int KILL_INDEX = 5;   // index of the killed==1 event in EXPECTED_EVENTS

// --- transport accounting (event windows emitted by the server / received by the client) ---
constexpr unsigned N_WINDOWS = 41u;
constexpr unsigned DELIVERED = 36u;

// --- full-reconstruction digest (SHA-256 over the client's applied event log) ---
constexpr const char* EVENT_DIGEST = "2a9ae8a3a929a25ab6be6abcace9f82c9387f46716eb898624d175dec10b490a";

// --- reliability-bound vector: a K-consecutive-frame blackout (aged-out early hits lost, 
//     journal resyncs, kill still delivered) — the client recovers exactly these seqs ---
constexpr std::int64_t BLACKOUT_DROPS[] = { 40, 45, 50 };
constexpr unsigned BLACKOUT_N_DROPS = 3u;
constexpr std::int64_t BLACKOUT_APPLIED_SEQS[] = { 2, 3, 4, 5 };
constexpr int BLACKOUT_APPLIED_COUNT = 4;
constexpr const char* BLACKOUT_DIGEST = "3d776f7db879cd8a991358501e7c5d803c72daaad41aaae7e7e1e4aafc3d66ac";

// --- EVENT-MULTIHIT-001: the per-round GRANULARITY scenario (twin shooters, one target;
//     every volley = two rounds on the SAME tick -> two attributed events; the kill volley
//     shows the overkill clamp). Envelopes reused from sess_vec (identical bake). ---
constexpr session::Phase MH_SCHED_0[] = {
  {0u, 0x0.0p+0, 0x1.0000000000000p+0, 0x1.b333333333333p-1, true},
  {9u, 0x0.0p+0, 0x1.0000000000000p+0, 0x1.b333333333333p-1, false},
};
constexpr session::Phase MH_SCHED_1[] = {
  {0u, 0x0.0p+0, 0x1.0000000000000p+0, 0x1.b333333333333p-1, true},
  {9u, 0x0.0p+0, 0x1.0000000000000p+0, 0x1.b333333333333p-1, false},
};
constexpr session::Phase MH_SCHED_2[] = {
  {0u, 0x0.0p+0, 0x1.0000000000000p+0, 0x1.6666666666666p-1, false},
};
constexpr session::AircraftSpec MH_AIRCRAFT[] = {
  { &sess_vec::ENV_P47D, 0x1.c987103b761f5p-9, 0x0.0p+0, 0x1.921fb54442d18p+0, 0x0.0p+0, 0x1.7700000000000p+11, 0x1.9000000000000p+7, MH_SCHED_0, 2u },
  { &sess_vec::ENV_P47D, -0x1.c987103b761f5p-9, 0x0.0p+0, 0x1.921fb54442d18p+0, 0x0.0p+0, 0x1.7700000000000p+11, 0x1.9000000000000p+7, MH_SCHED_1, 2u },
  { &sess_vec::ENV_A6M2, 0x0.0p+0, 0x1.acee9f37bebd6p-6, 0x1.921fb54442d18p+0, 0x0.0p+0, 0x1.7700000000000p+11, 0x1.2c00000000000p+7, MH_SCHED_2, 1u },
};
constexpr std::int64_t MH_DROP_EMIT_TICKS[] = { 50 };
constexpr session::Scenario MH_SCENARIO = {
  MH_AIRCRAFT, 3u, 120u, 5u, 10u, 15u,
  MH_DROP_EMIT_TICKS, 1u
};

constexpr ExpectEvent MH_EXPECTED_EVENTS[] = {
  { 0, 43, 2, 12000, 58000, 0, 0 },
  { 1, 43, 2, 12000, 46000, 0, 1 },
  { 2, 46, 2, 12000, 34000, 0, 0 },
  { 3, 46, 2, 12000, 22000, 0, 1 },
  { 4, 49, 2, 12000, 10000, 0, 0 },
  { 5, 49, 2, 10000, 0, 1, 1 },
};
constexpr int MH_EXPECTED_EVENT_COUNT = sizeof(MH_EXPECTED_EVENTS)/sizeof(MH_EXPECTED_EVENTS[0]);
constexpr int MH_KILL_INDEX = 5;
constexpr unsigned MH_N_WINDOWS = 25u;
constexpr unsigned MH_DELIVERED = 22u;
constexpr const char* MH_EVENT_DIGEST = "2d21822e99b2fbeb0b78cfea17e9d2d30d4a560fc91663444122563027b4d6af";

}} // namespace seads::event_vec
