// AUTO-GENERATED by tools/gen_interp_vectors.py — DO NOT EDIT.
// Remote interpolation (netcode layer 4a) parity vectors: C++ seads_net vs tools/interp_ref.py.
#pragma once
#include <cstdint>
namespace seads { namespace interp_vec {

struct IEnt   { long long id; double lat_deg; double lon_deg;
                double bearing_deg; double alt_m; };
struct IFrame { long long server_tick; const IEnt* ents; int n; };
struct ICase  { const char* label; const IFrame* frames; int n_frames;
                double render_tick; const IEnt* expect; int n_expect; };

constexpr IEnt C0_F0_ENTS[] = {
  { 1LL, 0x0.0p+0, 0x0.0p+0, 0x1.4000000000000p+3, 0x1.f400000000000p+9 },
};
constexpr IEnt C0_F1_ENTS[] = {
  { 1LL, 0x1.0000000000000p+1, -0x1.0000000000000p+2, 0x1.9000000000000p+5, 0x1.f400000000000p+10 },
};
constexpr IFrame C0_FRAMES[] = {
  { 0LL, C0_F0_ENTS, 1 },
  { 10LL, C0_F1_ENTS, 1 },
};
constexpr IEnt C0_EXPECT[] = {
  { 1LL, 0x1.0000000000000p+0, -0x1.0000000000000p+1, 0x1.e000000000000p+4, 0x1.7700000000000p+10 },
};

constexpr IEnt C1_F0_ENTS[] = {
  { 1LL, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0 },
};
constexpr IEnt C1_F1_ENTS[] = {
  { 1LL, 0x1.0000000000000p+3, 0x1.0000000000000p+4, 0x1.4000000000000p+6, 0x1.f400000000000p+11 },
};
constexpr IFrame C1_FRAMES[] = {
  { 0LL, C1_F0_ENTS, 1 },
  { 8LL, C1_F1_ENTS, 1 },
};
constexpr IEnt C1_EXPECT[] = {
  { 1LL, 0x1.0000000000000p+1, 0x1.0000000000000p+2, 0x1.4000000000000p+4, 0x1.f400000000000p+9 },
};

constexpr IEnt C2_F0_ENTS[] = {
  { 1LL, 0x1.0000000000000p+0, 0x1.0000000000000p+1, 0x1.5e00000000000p+8, 0x1.f400000000000p+8 },
};
constexpr IEnt C2_F1_ENTS[] = {
  { 1LL, 0x1.0000000000000p+0, 0x1.0000000000000p+1, 0x1.4000000000000p+3, 0x1.f400000000000p+8 },
};
constexpr IFrame C2_FRAMES[] = {
  { 100LL, C2_F0_ENTS, 1 },
  { 110LL, C2_F1_ENTS, 1 },
};
constexpr IEnt C2_EXPECT[] = {
  { 1LL, 0x1.0000000000000p+0, 0x1.0000000000000p+1, 0x0.0p+0, 0x1.f400000000000p+8 },
};

constexpr IEnt C3_F0_ENTS[] = {
  { 1LL, 0x0.0p+0, 0x0.0p+0, 0x1.4000000000000p+3, 0x0.0p+0 },
};
constexpr IEnt C3_F1_ENTS[] = {
  { 1LL, 0x0.0p+0, 0x0.0p+0, 0x1.5e00000000000p+8, 0x0.0p+0 },
};
constexpr IFrame C3_FRAMES[] = {
  { 0LL, C3_F0_ENTS, 1 },
  { 10LL, C3_F1_ENTS, 1 },
};
constexpr IEnt C3_EXPECT[] = {
  { 1LL, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0 },
};

constexpr IEnt C4_F0_ENTS[] = {
  { 1LL, 0x1.4000000000000p+2, 0x1.5400000000000p+7, 0x0.0p+0, 0x0.0p+0 },
};
constexpr IEnt C4_F1_ENTS[] = {
  { 1LL, 0x1.4000000000000p+2, -0x1.5400000000000p+7, 0x0.0p+0, 0x0.0p+0 },
};
constexpr IFrame C4_FRAMES[] = {
  { 0LL, C4_F0_ENTS, 1 },
  { 10LL, C4_F1_ENTS, 1 },
};
constexpr IEnt C4_EXPECT[] = {
  { 1LL, 0x1.4000000000000p+2, 0x1.6800000000000p+7, 0x0.0p+0, 0x0.0p+0 },
};

constexpr IEnt C5_F0_ENTS[] = {
  { 1LL, 0x1.4000000000000p+2, 0x1.4000000000000p+2, 0x1.6800000000000p+6, 0x1.9000000000000p+6 },
};
constexpr IEnt C5_F1_ENTS[] = {
  { 1LL, 0x1.8000000000000p+2, 0x1.4000000000000p+2, 0x1.6800000000000p+6, 0x1.9000000000000p+6 },
};
constexpr IFrame C5_FRAMES[] = {
  { 20LL, C5_F0_ENTS, 1 },
  { 30LL, C5_F1_ENTS, 1 },
};
constexpr IEnt C5_EXPECT[] = {
  { 1LL, 0x1.4000000000000p+2, 0x1.4000000000000p+2, 0x1.6800000000000p+6, 0x1.9000000000000p+6 },
};

constexpr IEnt C6_F0_ENTS[] = {
  { 1LL, 0x1.4000000000000p+2, 0x1.4000000000000p+2, 0x1.6800000000000p+6, 0x1.9000000000000p+6 },
};
constexpr IEnt C6_F1_ENTS[] = {
  { 1LL, 0x1.8000000000000p+2, 0x1.4000000000000p+2, 0x1.6800000000000p+6, 0x1.9000000000000p+6 },
};
constexpr IFrame C6_FRAMES[] = {
  { 20LL, C6_F0_ENTS, 1 },
  { 30LL, C6_F1_ENTS, 1 },
};
constexpr IEnt C6_EXPECT[] = {
  { 1LL, 0x1.8000000000000p+2, 0x1.4000000000000p+2, 0x1.6800000000000p+6, 0x1.9000000000000p+6 },
};

constexpr IEnt C7_F0_ENTS[] = {
  { 1LL, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0 },
  { 2LL, 0x1.4000000000000p+3, 0x1.4000000000000p+3, 0x1.6800000000000p+6, 0x1.f400000000000p+8 },
};
constexpr IEnt C7_F1_ENTS[] = {
  { 1LL, 0x1.0000000000000p+2, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0 },
};
constexpr IFrame C7_FRAMES[] = {
  { 0LL, C7_F0_ENTS, 2 },
  { 4LL, C7_F1_ENTS, 1 },
};
constexpr IEnt C7_EXPECT[] = {
  { 1LL, 0x1.0000000000000p+1, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0 },
  { 2LL, 0x1.4000000000000p+3, 0x1.4000000000000p+3, 0x1.6800000000000p+6, 0x1.f400000000000p+8 },
};

constexpr IEnt C8_F0_ENTS[] = {
  { 7LL, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0, 0x0.0p+0 },
};
constexpr IEnt C8_F1_ENTS[] = {
  { 7LL, 0x1.4000000000000p+2, -0x1.4000000000000p+2, 0x1.6800000000000p+5, 0x1.f400000000000p+7 },
};
constexpr IEnt C8_F2_ENTS[] = {
  { 7LL, 0x1.4000000000000p+2, 0x1.4000000000000p+2, 0x1.6800000000000p+6, 0x1.7700000000000p+9 },
};
constexpr IFrame C8_FRAMES[] = {
  { 0LL, C8_F0_ENTS, 1 },
  { 5LL, C8_F1_ENTS, 1 },
  { 15LL, C8_F2_ENTS, 1 },
};
constexpr IEnt C8_EXPECT[] = {
  { 7LL, 0x1.4000000000000p+2, 0x0.0p+0, 0x1.0e00000000000p+6, 0x1.f400000000000p+8 },
};

constexpr IEnt C9_F0_ENTS[] = {
  { 3LL, 0x1.8b0fcd324d5a2p+3, -0x1.8b0fcd6eb33c0p+6, 0x1.0e00000000000p+8, 0x1.f3fffbe76c8b4p+12 },
  { 5LL, -0x1.6c00000000000p+5, 0x1.67fffffca501bp+7, 0x0.0p+0, 0x1.4000000000000p+3 },
};
constexpr IEnt C9_F1_ENTS[] = {
  { 3LL, 0x1.8cccccccccccdp+3, -0x1.8accccccccccdp+6, 0x1.1080000000000p+8, 0x1.f3f8000000000p+12 },
  { 5LL, -0x1.6b33333333333p+5, -0x1.67fffffca501bp+7, 0x1.6780000000000p+8, 0x1.8000000000000p+3 },
};
constexpr IFrame C9_FRAMES[] = {
  { 1000LL, C9_F0_ENTS, 2 },
  { 1005LL, C9_F1_ENTS, 2 },
};
constexpr IEnt C9_EXPECT[] = {
  { 3LL, 0x1.8bee4cff8d138p+3, -0x1.8aee4d1dc0046p+6, 0x1.0f40000000000p+8, 0x1.f3fbfdf3b645ap+12 },
  { 5LL, -0x1.6b9999999999ap+5, 0x1.6800000000000p+7, 0x1.67c0000000000p+8, 0x1.6000000000000p+3 },
};

constexpr ICase CASES[] = {
  { "midpoint", C0_FRAMES, 2, 0x1.4000000000000p+2, C0_EXPECT, 1 },
  { "quarter", C1_FRAMES, 2, 0x1.0000000000000p+1, C1_EXPECT, 1 },
  { "bearing_seam", C2_FRAMES, 2, 0x1.a400000000000p+6, C2_EXPECT, 1 },
  { "bearing_seam_down", C3_FRAMES, 2, 0x1.4000000000000p+2, C3_EXPECT, 1 },
  { "lon_antimeridian", C4_FRAMES, 2, 0x1.4000000000000p+2, C4_EXPECT, 1 },
  { "hold_before_first", C5_FRAMES, 2, 0x1.4000000000000p+3, C5_EXPECT, 1 },
  { "hold_after_last", C6_FRAMES, 2, 0x1.8c00000000000p+6, C6_EXPECT, 1 },
  { "multi_entity_one_missing", C7_FRAMES, 2, 0x1.0000000000000p+1, C7_EXPECT, 2 },
  { "three_frames_interior", C8_FRAMES, 3, 0x1.4000000000000p+3, C8_EXPECT, 1 },
  { "realistic_decoded_degrees", C9_FRAMES, 2, 0x1.f540000000000p+9, C9_EXPECT, 2 },
};
constexpr int CASE_COUNT = sizeof(CASES)/sizeof(CASES[0]);

}} // namespace seads::interp_vec
