// AUTO-GENERATED by tools/gen_lockstep_vectors.py — DO NOT EDIT.
// Loopback lockstep (netcode layer 3) parity vectors: C++ harness vs tools/lockstep_ref.py.
// Self-contained scripted timeline + expected per-tick world_hash digest/checkpoints.
#pragma once
#include <cstdint>
#include "flight_types.h"   // seads::Envelope, Command (from the kernel include dir)
namespace seads { namespace ls_vec {

// --- tuning envelopes used by the scenario (deg->rad baked, hex-float, kernel-identical) ---
constexpr Envelope ENV_KI61 = {
  /*phi_max*/ {{0x1.4000000000000p+5, 0x1.e000000000000p+5, 0x1.9000000000000p+6, 0x1.1800000000000p+7, 0x1.5400000000000p+7}, {0x1.0c152382d7365p+0, 0x1.eb7c166fdfe3ap-1, 0x1.becde5da115a9p-1, 0x1.921fb54442d18p-1, 0x1.657184ae74487p-1}},
  /*roll_rate*/ {{0x1.4000000000000p+5, 0x1.4000000000000p+6, 0x1.e000000000000p+6, 0x1.4000000000000p+7, 0x1.5400000000000p+7}, {0x1.657184ae74487p+0, 0x1.921fb54442d18p+0, 0x1.becde5da115a9p+0, 0x1.a876cd8f2a161p+0, 0x1.921fb54442d18p+0}},
  /*climb_max*/ {{0x1.4000000000000p+5, 0x1.4000000000000p+6, 0x1.e000000000000p+6, 0x1.4000000000000p+7, 0x1.5400000000000p+7}, {0x1.e000000000000p+3, 0x1.8000000000000p+3, 0x1.4000000000000p+3, 0x1.0000000000000p+3, 0x1.c000000000000p+2}},
  /*climb_min*/ {{0x1.4000000000000p+5, 0x1.4000000000000p+6, 0x1.e000000000000p+6, 0x1.4000000000000p+7, 0x1.5400000000000p+7}, {-0x1.4000000000000p+4, -0x1.2000000000000p+4, -0x1.e000000000000p+3, -0x1.8000000000000p+3, -0x1.4000000000000p+3}}
};
constexpr Envelope ENV_BF109F4 = {
  /*phi_max*/ {{0x1.5000000000000p+5, 0x1.4000000000000p+6, 0x1.e000000000000p+6, 0x1.4000000000000p+7, 0x1.7200000000000p+7}, {0x1.03258031ade7cp+0, 0x1.e28c731eb6950p-1, 0x1.b5de4288e80bfp-1, 0x1.893011f31982ep-1, 0x1.6e6127ff9d971p-1}},
  /*roll_rate*/ {{0x1.5000000000000p+5, 0x1.4000000000000p+6, 0x1.e000000000000p+6, 0x1.4000000000000p+7, 0x1.7200000000000p+7}, {0x1.4f1a6c638d03fp+0, 0x1.657184ae74487p+0, 0x1.5c81e15d4af9dp+0, 0x1.38c35418a5bf6p+0, 0x1.1504c6d40084fp+0}},
  /*climb_max*/ {{0x1.5000000000000p+5, 0x1.4000000000000p+6, 0x1.e000000000000p+6, 0x1.4000000000000p+7, 0x1.7200000000000p+7}, {0x1.3000000000000p+4, 0x1.0000000000000p+4, 0x1.a000000000000p+3, 0x1.4000000000000p+3, 0x1.2000000000000p+3}},
  /*climb_min*/ {{0x1.5000000000000p+5, 0x1.4000000000000p+6, 0x1.e000000000000p+6, 0x1.4000000000000p+7, 0x1.7200000000000p+7}, {-0x1.4000000000000p+4, -0x1.7000000000000p+4, -0x1.a000000000000p+4, -0x1.c000000000000p+4, -0x1.e000000000000p+4}}
};
constexpr Envelope ENV_SPITFIRE_MK5 = {
  /*phi_max*/ {{0x1.4000000000000p+5, 0x1.4000000000000p+6, 0x1.e000000000000p+6, 0x1.4000000000000p+7, 0x1.7c00000000000p+7}, {0x1.197c987c952c4p+0, 0x1.079d51da428f1p+0, 0x1.d99ccfcd8d466p-1, 0x1.a3fefbe6956ecp-1, 0x1.893011f31982ep-1}},
  /*roll_rate*/ {{0x1.4000000000000p+5, 0x1.4000000000000p+6, 0x1.e000000000000p+6, 0x1.4000000000000p+7, 0x1.7c00000000000p+7}, {0x1.41b2f769cf0e0p+0, 0x1.657184ae74487p+0, 0x1.6e6127ff9d971p+0, 0x1.5c81e15d4af9dp+0, 0x1.41b2f769cf0e0p+0}},
  /*climb_max*/ {{0x1.4000000000000p+5, 0x1.4000000000000p+6, 0x1.e000000000000p+6, 0x1.4000000000000p+7, 0x1.7c00000000000p+7}, {0x1.2000000000000p+4, 0x1.e000000000000p+3, 0x1.8000000000000p+3, 0x1.4000000000000p+3, 0x1.2000000000000p+3}},
  /*climb_min*/ {{0x1.4000000000000p+5, 0x1.4000000000000p+6, 0x1.e000000000000p+6, 0x1.4000000000000p+7, 0x1.7c00000000000p+7}, {-0x1.5000000000000p+4, -0x1.8000000000000p+4, -0x1.b000000000000p+4, -0x1.e000000000000p+4, -0x1.0000000000000p+5}}
};
constexpr const Envelope* ENVELOPES[] = {
    &ENV_KI61, &ENV_BF109F4, &ENV_SPITFIRE_MK5
};

struct Phase  { unsigned start_tick; double target_phi; double target_climb; };
struct AcSpec { double lat, lon, psi, phi, alt, tas; int env_idx;
                const Phase* sched; unsigned n_phase; };

constexpr Phase AC0_SCHED[] = {
  {0u, 0x0.0p+0, 0x0.0p+0},
  {150u, 0x1.921fb54442d18p-1, 0x1.4000000000000p+2},
  {400u, -0x1.0c152382d7365p-1, -0x1.8000000000000p+1},
};
constexpr Phase AC1_SCHED[] = {
  {0u, 0x0.0p+0, 0x1.0000000000000p+3},
  {250u, 0x1.0c152382d7365p+0, 0x0.0p+0},
};
constexpr Phase AC2_SCHED[] = {
  {0u, 0x0.0p+0, 0x1.4000000000000p+4},
  {300u, -0x1.657184ae74487p-1, 0x0.0p+0},
};
constexpr AcSpec AIRCRAFT[] = {
  { 0x0.0p+0, 0x0.0p+0, 0x1.921fb54442d18p-1, 0x0.0p+0, 0x1.f400000000000p+10, 0x1.1800000000000p+7, 0, AC0_SCHED, 3u },
  { 0x1.657184ae74487p-3, -0x1.657184ae74487p-2, 0x1.921fb54442d18p+0, 0x0.0p+0, 0x1.7700000000000p+11, 0x1.4000000000000p+7, 1, AC1_SCHED, 2u },
  { -0x1.0c152382d7365p-2, 0x1.0c152382d7365p-1, 0x1.2d97c7f3321d2p+2, 0x0.0p+0, 0x1.f0e0000000000p+12, 0x1.2c00000000000p+7, 2, AC2_SCHED, 2u },
};
constexpr unsigned N_AIRCRAFT = 3u;
constexpr unsigned TICKS      = 600u;

struct Checkpoint { unsigned tick; const char* hash; };
constexpr Checkpoint CHECKPOINTS[] = {
  { 1u, "6e1d1997c384b47cfc029d5807c5ac1ad276bcdf89ce1860637c913a5e3ebd4c" },
  { 100u, "4e2710d63f9ec599985269ad86edd168ec0c52f50aed5b36815a04b1bbd1a72c" },
  { 200u, "c56d1d89e044b08bc1624ac158af84184b6c4ad35795926c913a8b8eedcc1ea7" },
  { 300u, "cec5deaab7626b959e3cbe63c1a3baa5e1752b2b582320242a6be8d755a1e479" },
  { 400u, "3bc7d136fe2dc0198e2827aa8ef38ecb16d8d12cf2293459d6d7c7b83937170c" },
  { 500u, "aada75dbb0bd61955a928cca827d259cd13788ae62c3dde4abeff7fc40fa2758" },
  { 600u, "d60868028548ab48ecb85ead9dd1a68abc10d1cb3f460aedd9a45ed5b08d3a55" },
};
constexpr int CHECKPOINT_COUNT = sizeof(CHECKPOINTS)/sizeof(CHECKPOINTS[0]);

constexpr const char* SEQUENCE_DIGEST = "2f7fa22b74f1e362fd55c0dda3acc6edd6b363ab87b2d952b82ae9f36aaa5c0d";

}} // namespace seads::ls_vec
