// AUTO-GENERATED by tools/gen_predict_vectors.py — DO NOT EDIT.
// Client-side prediction (netcode layer 4b) parity vectors: C++ harness vs
// tools/predict_ref.py. Self-contained scripted scenario + expected predicted
// per-tick world_hash digest/checkpoints + the perturbation heal tick.
#pragma once
#include <cstdint>
#include "flight_types.h"   // seads::Envelope, Command (from the kernel include dir)
namespace seads { namespace pred_vec {

// --- tuning envelope used by the scenario (deg->rad baked, hex-float, kernel-identical) ---
constexpr Envelope ENV_KI61 = {
  /*phi_max*/ {{0x1.4000000000000p+5, 0x1.e000000000000p+5, 0x1.9000000000000p+6, 0x1.1800000000000p+7, 0x1.5400000000000p+7}, {0x1.0c152382d7365p+0, 0x1.eb7c166fdfe3ap-1, 0x1.becde5da115a9p-1, 0x1.921fb54442d18p-1, 0x1.657184ae74487p-1}},
  /*roll_rate*/ {{0x1.4000000000000p+5, 0x1.4000000000000p+6, 0x1.e000000000000p+6, 0x1.4000000000000p+7, 0x1.5400000000000p+7}, {0x1.657184ae74487p+0, 0x1.921fb54442d18p+0, 0x1.becde5da115a9p+0, 0x1.a876cd8f2a161p+0, 0x1.921fb54442d18p+0}},
  /*climb_max*/ {{0x1.4000000000000p+5, 0x1.4000000000000p+6, 0x1.e000000000000p+6, 0x1.4000000000000p+7, 0x1.5400000000000p+7}, {0x1.e000000000000p+3, 0x1.8000000000000p+3, 0x1.4000000000000p+3, 0x1.0000000000000p+3, 0x1.c000000000000p+2}},
  /*climb_min*/ {{0x1.4000000000000p+5, 0x1.4000000000000p+6, 0x1.e000000000000p+6, 0x1.4000000000000p+7, 0x1.5400000000000p+7}, {-0x1.4000000000000p+4, -0x1.2000000000000p+4, -0x1.e000000000000p+3, -0x1.8000000000000p+3, -0x1.4000000000000p+3}},
  0x1.8380000000000p+11, 0x1.4000000000000p+4, 0x1.89374bc6a7efap-6, 0x1.db22d0e560419p-5, 0x1.3ba0000000000p+13, 0x1.6800000000000p+8, 0x1.8d0e560418937p+0, 0x1.e000000000000p+2, -0x1.c000000000000p+1, 0x1.7c00000000000p+6, 0x1.9000000000000p+9, 0x1.c000000000000p+3, 0x1.8000000000000p+2, 0x1.7c00000000000p+7, 0x1.cc00000000000p+7, 0x1.0000000000000p-2, 0x1.0000000000000p-1, 0x1.0000000000000p-2, 0x1.f400000000000p+11, 0x0.0p+0, 0x1.0000000000000p+0
};
constexpr const Envelope* ENVELOPE = &ENV_KI61;

// --- own-aircraft initial state (radians / metres / m s^-1) ---
struct Start { double lat, lon, psi, phi, alt, tas; };
constexpr Start START = { 0x0.0p+0, 0x0.0p+0, 0x1.921fb54442d18p-1, 0x0.0p+0, 0x1.f400000000000p+10, 0x1.2c00000000000p+7 };

// --- command schedule (target_phi in RADIANS, pre-converted; integer phase select) ---
struct Phase { unsigned start_tick; double target_phi; double target_g; double throttle; };
constexpr Phase SCHED[] = {
  {0u, 0x0.0p+0, 0x1.0000000000000p+0, 0x1.999999999999ap-1},
  {60u, 0x1.921fb54442d18p-1, 0x1.8000000000000p+0, 0x1.999999999999ap-1},
  {180u, -0x1.0c152382d7365p-1, 0x1.3333333333333p-1, 0x1.999999999999ap-1},
};
constexpr unsigned N_PHASE    = 3u;
constexpr unsigned TICKS      = 300u;
constexpr unsigned SNAP_EVERY = 5u;
constexpr unsigned LAG_TICKS  = 10u;
constexpr double   PERTURB_ALT = 0x1.0000000000000p-20;  // negative-control alt desync
constexpr unsigned HEAL_TICK   = 15u;             // perturbed predictor heals here

// --- expected nominal predicted per-tick hash checkpoints + whole-sequence digest ---
struct Checkpoint { unsigned tick; const char* hash; };
constexpr Checkpoint CHECKPOINTS[] = {
  { 1u, "6af62de762458e1c50254f6d3b29f226d1f0772ac237ff1fafad0e8d257d1b1f" },
  { 50u, "f057b209871d1ace71d00251b1653e39506b57948eeb75558934bd88dd2ae1d2" },
  { 100u, "2568c1e7ee3a36d084c1ff9070d28b21ae41362e1dd627b23b431dcac43a608b" },
  { 150u, "39abfe8671fa2e0183ca9f9202192d44d76877bd31b6ecaa7072e2584311c30b" },
  { 200u, "6527a12b19d31fd64b7471e36687d1c9360dbbb73522c451f4ed71e69ecc74f9" },
  { 250u, "c7b50f9bfdf0b11cf6ee4de90a079ad4b4e0db8e6c9f6edfa204707afd986d6d" },
  { 300u, "f30b8cb34de22f578393d51a8dffcd531d16f0c254b5560b451fe03ffda7d026" },
};
constexpr int CHECKPOINT_COUNT = sizeof(CHECKPOINTS)/sizeof(CHECKPOINTS[0]);

constexpr const char* SEQUENCE_DIGEST = "31dfc22239e8600e67b303cf54acbf40421e0b6389d2e3de3ef0026d7438806c";

}} // namespace seads::pred_vec
