// AUTO-GENERATED by tools/gen_predict_vectors.py — DO NOT EDIT.
// Client-side prediction (netcode layer 4b) parity vectors: C++ harness vs
// tools/predict_ref.py. Self-contained scripted scenario + expected predicted
// per-tick world_hash digest/checkpoints + the perturbation heal tick.
#pragma once
#include <cstdint>
#include "flight_types.h"   // seads::Envelope, Command (from the kernel include dir)
namespace seads { namespace pred_vec {

// --- tuning envelope used by the scenario (deg->rad baked, hex-float, kernel-identical) ---
constexpr Envelope ENV_KI61 = {
  /*phi_max*/ {{0x1.4000000000000p+5, 0x1.e000000000000p+5, 0x1.9000000000000p+6, 0x1.1800000000000p+7, 0x1.5400000000000p+7}, {0x1.0c152382d7365p+0, 0x1.eb7c166fdfe3ap-1, 0x1.becde5da115a9p-1, 0x1.921fb54442d18p-1, 0x1.657184ae74487p-1}},
  /*roll_rate*/ {{0x1.4000000000000p+5, 0x1.4000000000000p+6, 0x1.e000000000000p+6, 0x1.4000000000000p+7, 0x1.5400000000000p+7}, {0x1.657184ae74487p+0, 0x1.921fb54442d18p+0, 0x1.becde5da115a9p+0, 0x1.a876cd8f2a161p+0, 0x1.921fb54442d18p+0}},
  /*climb_max*/ {{0x1.4000000000000p+5, 0x1.4000000000000p+6, 0x1.e000000000000p+6, 0x1.4000000000000p+7, 0x1.5400000000000p+7}, {0x1.e000000000000p+3, 0x1.8000000000000p+3, 0x1.4000000000000p+3, 0x1.0000000000000p+3, 0x1.c000000000000p+2}},
  /*climb_min*/ {{0x1.4000000000000p+5, 0x1.4000000000000p+6, 0x1.e000000000000p+6, 0x1.4000000000000p+7, 0x1.5400000000000p+7}, {-0x1.4000000000000p+4, -0x1.2000000000000p+4, -0x1.e000000000000p+3, -0x1.8000000000000p+3, -0x1.4000000000000p+3}},
  0x1.8380000000000p+11, 0x1.4000000000000p+4, 0x1.89374bc6a7efap-6, 0x1.db22d0e560419p-5, 0x1.4960000000000p+13, 0x1.5e00000000000p+9, 0x1.8d0e560418937p+0, 0x1.e000000000000p+2, -0x1.c000000000000p+1, 0x1.7c00000000000p+6, 0x1.9000000000000p+9, 0x1.c000000000000p+3, 0x1.8000000000000p+2, 0x1.7c00000000000p+7, 0x1.cc00000000000p+7, 0x1.0000000000000p-2, 0x1.0000000000000p-1, 0x1.0000000000000p-2
};
constexpr const Envelope* ENVELOPE = &ENV_KI61;

// --- own-aircraft initial state (radians / metres / m s^-1) ---
struct Start { double lat, lon, psi, phi, alt, tas; };
constexpr Start START = { 0x0.0p+0, 0x0.0p+0, 0x1.921fb54442d18p-1, 0x0.0p+0, 0x1.f400000000000p+10, 0x1.2c00000000000p+7 };

// --- command schedule (target_phi in RADIANS, pre-converted; integer phase select) ---
struct Phase { unsigned start_tick; double target_phi; double target_g; double throttle; };
constexpr Phase SCHED[] = {
  {0u, 0x0.0p+0, 0x1.0000000000000p+0, 0x1.999999999999ap-1},
  {60u, 0x1.921fb54442d18p-1, 0x1.8000000000000p+0, 0x1.999999999999ap-1},
  {180u, -0x1.0c152382d7365p-1, 0x1.3333333333333p-1, 0x1.999999999999ap-1},
};
constexpr unsigned N_PHASE    = 3u;
constexpr unsigned TICKS      = 300u;
constexpr unsigned SNAP_EVERY = 5u;
constexpr unsigned LAG_TICKS  = 10u;
constexpr double   PERTURB_ALT = 0x1.0000000000000p-20;  // negative-control alt desync
constexpr unsigned HEAL_TICK   = 15u;             // perturbed predictor heals here

// --- expected nominal predicted per-tick hash checkpoints + whole-sequence digest ---
struct Checkpoint { unsigned tick; const char* hash; };
constexpr Checkpoint CHECKPOINTS[] = {
  { 1u, "9930d18e89d3ce72049034470214de63620e6d2159f9eca13a45e0d9357d3c99" },
  { 50u, "ab9beec5b75fdc17be27cd9c275f541d44271a7e9875d42e47a24680feb015a6" },
  { 100u, "a784407c28c441b147f7ab2174aaf3b52d9286a7795d0be8c27b153440a1964b" },
  { 150u, "15a3388864fc3d84012075c7fb11ad2102c2bb1a3883aeee69a1835f9754dd96" },
  { 200u, "5433630b0eeeb00dd799d97f396c7574b7c31f1c58084f204ce53a1a2c602b25" },
  { 250u, "0b0dd723f5c91e197030599154d96de1dc54ba9bbad5183bbbc975383f2f0eb1" },
  { 300u, "de931373d4119a198621b815a027846ffbb0f204185411e184535d1f01fbc2d0" },
};
constexpr int CHECKPOINT_COUNT = sizeof(CHECKPOINTS)/sizeof(CHECKPOINTS[0]);

constexpr const char* SEQUENCE_DIGEST = "a984faa741788d3d08ff4e34d89b81d388fb97edc6c49f14e92f39a474bc0f0e";

}} // namespace seads::pred_vec
