// AUTO-GENERATED by tools/gen_predict_vectors.py — DO NOT EDIT.
// Client-side prediction (netcode layer 4b) parity vectors: C++ harness vs
// tools/predict_ref.py. Self-contained scripted scenario + expected predicted
// per-tick world_hash digest/checkpoints + the perturbation heal tick.
#pragma once
#include <cstdint>
#include "flight_types.h"   // seads::Envelope, Command (from the kernel include dir)
namespace seads { namespace pred_vec {

// --- tuning envelope used by the scenario (deg->rad baked, hex-float, kernel-identical) ---
constexpr Envelope ENV_KI61 = {
  /*phi_max*/ {{0x1.4000000000000p+5, 0x1.e000000000000p+5, 0x1.9000000000000p+6, 0x1.1800000000000p+7, 0x1.5400000000000p+7}, {0x1.0c152382d7365p+0, 0x1.eb7c166fdfe3ap-1, 0x1.becde5da115a9p-1, 0x1.921fb54442d18p-1, 0x1.657184ae74487p-1}},
  /*roll_rate*/ {{0x1.4000000000000p+5, 0x1.4000000000000p+6, 0x1.e000000000000p+6, 0x1.4000000000000p+7, 0x1.5400000000000p+7}, {0x1.657184ae74487p+0, 0x1.921fb54442d18p+0, 0x1.becde5da115a9p+0, 0x1.a876cd8f2a161p+0, 0x1.921fb54442d18p+0}},
  /*climb_max*/ {{0x1.4000000000000p+5, 0x1.4000000000000p+6, 0x1.e000000000000p+6, 0x1.4000000000000p+7, 0x1.5400000000000p+7}, {0x1.e000000000000p+3, 0x1.8000000000000p+3, 0x1.4000000000000p+3, 0x1.0000000000000p+3, 0x1.c000000000000p+2}},
  /*climb_min*/ {{0x1.4000000000000p+5, 0x1.4000000000000p+6, 0x1.e000000000000p+6, 0x1.4000000000000p+7, 0x1.5400000000000p+7}, {-0x1.4000000000000p+4, -0x1.2000000000000p+4, -0x1.e000000000000p+3, -0x1.8000000000000p+3, -0x1.4000000000000p+3}},
  0x1.8380000000000p+11, 0x1.4000000000000p+4, 0x1.89374bc6a7efap-6, 0x1.db22d0e560419p-5, 0x1.4960000000000p+13, 0x1.5e00000000000p+9, 0x1.8d0e560418937p+0, 0x1.e000000000000p+2, -0x1.c000000000000p+1
};
constexpr const Envelope* ENVELOPE = &ENV_KI61;

// --- own-aircraft initial state (radians / metres / m s^-1) ---
struct Start { double lat, lon, psi, phi, alt, tas; };
constexpr Start START = { 0x0.0p+0, 0x0.0p+0, 0x1.921fb54442d18p-1, 0x0.0p+0, 0x1.f400000000000p+10, 0x1.2c00000000000p+7 };

// --- command schedule (target_phi in RADIANS, pre-converted; integer phase select) ---
struct Phase { unsigned start_tick; double target_phi; double target_g; double throttle; };
constexpr Phase SCHED[] = {
  {0u, 0x0.0p+0, 0x1.0000000000000p+0, 0x1.999999999999ap-1},
  {60u, 0x1.921fb54442d18p-1, 0x1.8000000000000p+0, 0x1.999999999999ap-1},
  {180u, -0x1.0c152382d7365p-1, 0x1.3333333333333p-1, 0x1.999999999999ap-1},
};
constexpr unsigned N_PHASE    = 3u;
constexpr unsigned TICKS      = 300u;
constexpr unsigned SNAP_EVERY = 5u;
constexpr unsigned LAG_TICKS  = 10u;
constexpr double   PERTURB_ALT = 0x1.0000000000000p-20;  // negative-control alt desync
constexpr unsigned HEAL_TICK   = 15u;             // perturbed predictor heals here

// --- expected nominal predicted per-tick hash checkpoints + whole-sequence digest ---
struct Checkpoint { unsigned tick; const char* hash; };
constexpr Checkpoint CHECKPOINTS[] = {
  { 1u, "36c05c07210d0533158cea999b60e9e9391c6213c1986e9c7d2e251339858eec" },
  { 50u, "f451cd5551c556297758f79d9d91354c03cb93c09c4f84dadf383a82cb351a12" },
  { 100u, "db5348fbced58f7d6e4dd4c37b12e21892a1e7986ca29c8a496f048af0b2759e" },
  { 150u, "9b09f04c6c6722c7067d4f2874c3a079ba01e653f56139240efb60f9b80761ec" },
  { 200u, "3d928f2ef430846bd9a02bf8939e5c6db3e84fbec930e09f8c53e86969dda4bd" },
  { 250u, "bf02426e141a62e8d2d032768092cb2aff7105fa199415edf6be99cc01833055" },
  { 300u, "4b7ff301ef3a1abe599056ecf0c8f7bfa017f682da6d117bddc02287042e3a15" },
};
constexpr int CHECKPOINT_COUNT = sizeof(CHECKPOINTS)/sizeof(CHECKPOINTS[0]);

constexpr const char* SEQUENCE_DIGEST = "acaa248973ca64386159e1c36b952b4ed9f75e3fa28025b94ba049d8271c8b0c";

}} // namespace seads::pred_vec
