// AUTO-GENERATED by tools/gen_session_vectors.py — DO NOT EDIT.
// Server<->client SESSION loop (netcode layer 5) parity vectors: C++ harness vs
// tools/session_ref.py. Self-contained SESSION-SK-001 scenario (3 aircraft, cadence,
// latency, render delay, packet-loss set) + expected reconstructed client-view digest /
// checkpoints + the replicated final weapon state (the gun kill) + transport accounting.
#pragma once
#include <cstdint>
#include "session.h"   // seads::session::{Phase,AircraftSpec,Scenario}, Envelope, Command
namespace seads { namespace sess_vec {

// --- tuning envelopes used by the scenario (deg->rad baked, hex-float, kernel-identical) ---
constexpr Envelope ENV_P47D = {
  /*phi_max*/ {{0x1.7000000000000p+5, 0x1.6800000000000p+6, 0x1.1800000000000p+7, 0x1.6800000000000p+7, 0x1.9a00000000000p+7}, {0x1.d0ad2c7c63f7dp-1, 0x1.becde5da115a9p-1, 0x1.9b0f58956c202p-1, 0x1.7750cb50c6e5bp-1, 0x1.657184ae74487p-1}},
  /*roll_rate*/ {{0x1.7000000000000p+5, 0x1.6800000000000p+6, 0x1.1800000000000p+7, 0x1.6800000000000p+7, 0x1.9a00000000000p+7}, {0x1.4f1a6c638d03fp+0, 0x1.7bc89cf95b8d0p+0, 0x1.a876cd8f2a161p+0, 0x1.becde5da115a9p+0, 0x1.d524fe24f89f2p+0}},
  /*climb_max*/ {{0x1.7000000000000p+5, 0x1.6800000000000p+6, 0x1.1800000000000p+7, 0x1.6800000000000p+7, 0x1.9a00000000000p+7}, {0x1.c000000000000p+3, 0x1.a000000000000p+3, 0x1.6000000000000p+3, 0x1.2000000000000p+3, 0x1.0000000000000p+3}},
  /*climb_min*/ {{0x1.7000000000000p+5, 0x1.6800000000000p+6, 0x1.1800000000000p+7, 0x1.6800000000000p+7, 0x1.9a00000000000p+7}, {-0x1.6000000000000p+4, -0x1.a000000000000p+4, -0x1.e000000000000p+4, -0x1.1000000000000p+5, -0x1.2000000000000p+5}},
  0x1.7700000000000p+12, 0x1.be66666666666p+4, 0x1.6872b020c49bap-6, 0x1.eb851eb851eb8p-5, 0x1.3808000000000p+14, 0x1.1d00000000000p+8, 0x1.a083126e978d5p+0, 0x1.1000000000000p+3, -0x1.0000000000000p+2, 0x1.2c00000000000p+7, 0x1.a900000000000p+9, 0x1.8000000000000p+3, 0x1.8000000000000p+1, 0x1.5400000000000p+8, 0x1.0e00000000000p+8, 0x1.4000000000000p-1, 0x1.0000000000000p-1, 0x1.8000000000000p-2, 0x1.f400000000000p+12
};
constexpr Envelope ENV_A6M2 = {
  /*phi_max*/ {{0x1.3000000000000p+5, 0x1.1800000000000p+6, 0x1.b800000000000p+6, 0x1.1800000000000p+7, 0x1.4a00000000000p+7}, {0x1.226c3bcdbe7aep+0, 0x1.1504c6d40084fp+0, 0x1.f46bb9c109324p-1, 0x1.becde5da115a9p-1, 0x1.9b0f58956c202p-1}},
  /*roll_rate*/ {{0x1.3000000000000p+5, 0x1.1800000000000p+6, 0x1.b800000000000p+6, 0x1.1800000000000p+7, 0x1.4a00000000000p+7}, {0x1.38c35418a5bf6p+0, 0x1.2fd3b0c77c70dp+0, 0x1.eb7c166fdfe3ap-1, 0x1.921fb54442d18p-1, 0x1.53923e0c21ab4p-1}},
  /*climb_max*/ {{0x1.3000000000000p+5, 0x1.1800000000000p+6, 0x1.b800000000000p+6, 0x1.1800000000000p+7, 0x1.4a00000000000p+7}, {0x1.0000000000000p+4, 0x1.c000000000000p+3, 0x1.8000000000000p+3, 0x1.2000000000000p+3, 0x1.0000000000000p+3}},
  /*climb_min*/ {{0x1.3000000000000p+5, 0x1.1800000000000p+6, 0x1.b800000000000p+6, 0x1.1800000000000p+7, 0x1.4a00000000000p+7}, {-0x1.2000000000000p+4, -0x1.4000000000000p+4, -0x1.6000000000000p+4, -0x1.8000000000000p+4, -0x1.a000000000000p+4}},
  0x1.2c00000000000p+11, 0x1.6666666666666p+4, 0x1.89374bc6a7efap-6, 0x1.a9fbe76c8b439p-5, 0x1.32e0000000000p+13, 0x1.1d00000000000p+8, 0x1.3020c49ba5e35p+0, 0x1.c000000000000p+2, -0x1.8000000000000p+1, 0x1.1800000000000p+6, 0x1.4500000000000p+9, 0x1.4000000000000p+5, 0x1.2000000000000p+3, 0x1.9000000000000p+6, 0x1.f400000000000p+7, 0x1.0000000000000p-1, 0x1.8000000000000p-2, 0x1.0000000000000p-2, 0x1.1940000000000p+12
};
constexpr Envelope ENV_SPITFIRE_MK5 = {
  /*phi_max*/ {{0x1.4000000000000p+5, 0x1.4000000000000p+6, 0x1.e000000000000p+6, 0x1.4000000000000p+7, 0x1.7c00000000000p+7}, {0x1.197c987c952c4p+0, 0x1.079d51da428f1p+0, 0x1.d99ccfcd8d466p-1, 0x1.a3fefbe6956ecp-1, 0x1.893011f31982ep-1}},
  /*roll_rate*/ {{0x1.4000000000000p+5, 0x1.4000000000000p+6, 0x1.e000000000000p+6, 0x1.4000000000000p+7, 0x1.7c00000000000p+7}, {0x1.41b2f769cf0e0p+0, 0x1.657184ae74487p+0, 0x1.6e6127ff9d971p+0, 0x1.5c81e15d4af9dp+0, 0x1.41b2f769cf0e0p+0}},
  /*climb_max*/ {{0x1.4000000000000p+5, 0x1.4000000000000p+6, 0x1.e000000000000p+6, 0x1.4000000000000p+7, 0x1.7c00000000000p+7}, {0x1.2000000000000p+4, 0x1.e000000000000p+3, 0x1.8000000000000p+3, 0x1.4000000000000p+3, 0x1.2000000000000p+3}},
  /*climb_min*/ {{0x1.4000000000000p+5, 0x1.4000000000000p+6, 0x1.e000000000000p+6, 0x1.4000000000000p+7, 0x1.7c00000000000p+7}, {-0x1.5000000000000p+4, -0x1.8000000000000p+4, -0x1.b000000000000p+4, -0x1.e000000000000p+4, -0x1.0000000000000p+5}},
  0x1.6a80000000000p+11, 0x1.6800000000000p+4, 0x1.5810624dd2f1bp-6, 0x1.ba5e353f7ced9p-5, 0x1.5ef0000000000p+13, 0x1.1800000000000p+8, 0x1.4a3d70a3d70a4p+0, 0x1.0000000000000p+3, -0x1.c000000000000p+1, 0x1.9000000000000p+6, 0x1.9000000000000p+9, 0x1.a000000000000p+4, 0x1.4000000000000p+2, 0x1.2c00000000000p+7, 0x1.cc00000000000p+7, 0x1.0000000000000p-2, 0x1.0000000000000p-1, 0x1.0000000000000p-2, 0x1.7700000000000p+12
};

// --- per-aircraft command schedules (target_phi in RADIANS; integer phase select) ---
constexpr session::Phase SCHED_0[] = {
  {0u, 0x0.0p+0, 0x1.0000000000000p+0, 0x1.b333333333333p-1, true},
  {20u, 0x0.0p+0, 0x1.0000000000000p+0, 0x1.b333333333333p-1, false},
};
constexpr session::Phase SCHED_1[] = {
  {0u, 0x0.0p+0, 0x1.0000000000000p+0, 0x1.6666666666666p-1, false},
};
constexpr session::Phase SCHED_2[] = {
  {0u, 0x1.becde5da115a9p-2, 0x1.6666666666666p+0, 0x1.999999999999ap-1, false},
};

// --- aircraft specs (envelope + start state radians/metres/m s^-1 + schedule) ---
constexpr session::AircraftSpec AIRCRAFT[] = {
  { &ENV_P47D, 0x0.0p+0, 0x0.0p+0, 0x1.921fb54442d18p+0, 0x0.0p+0, 0x1.f400000000000p+11, 0x1.9000000000000p+7, SCHED_0, 2u },
  { &ENV_A6M2, 0x0.0p+0, 0x1.acee9f37bebd6p-6, 0x1.921fb54442d18p+0, 0x0.0p+0, 0x1.f400000000000p+11, 0x1.2c00000000000p+7, SCHED_1, 1u },
  { &ENV_SPITFIRE_MK5, 0x1.c987103b761f5p-9, 0x1.1df46a2529d39p-7, 0x1.38c35418a5bf6p+0, 0x0.0p+0, 0x1.0680000000000p+12, 0x1.6800000000000p+7, SCHED_2, 1u },
};
constexpr unsigned N_AIRCRAFT  = 3u;

constexpr std::int64_t DROP_EMIT_TICKS[] = { 30, 55, 80 };
constexpr unsigned N_DROPS     = 3u;

constexpr unsigned TICKS        = 200u;
constexpr unsigned SNAP_EVERY   = 5u;
constexpr unsigned LAG_TICKS    = 10u;
constexpr unsigned RENDER_DELAY = 15u;

// --- the assembled server-authoritative scenario ---
constexpr session::Scenario SCENARIO = {
  AIRCRAFT, N_AIRCRAFT, TICKS, SNAP_EVERY, LAG_TICKS, RENDER_DELAY,
  DROP_EMIT_TICKS, N_DROPS
};

// --- transport accounting (frames emitted by the server / received by the client) ---
constexpr unsigned N_FRAMES  = 41u;
constexpr unsigned DELIVERED = 36u;

// --- replicated final weapon state on the client (id, hp_milli = round(hp*1e3), dead, ammo = rounds remaining, last_hit_by = attacker index or -1, engine/wing/tail_milli = region sub-pools, kills = victory tally) ---
struct WeaponFact { std::int64_t id; std::int64_t hp_milli; int dead; std::int64_t ammo; std::int64_t last_hit_by; std::int64_t engine_milli; std::int64_t wing_milli; std::int64_t tail_milli; std::int64_t kills; };
constexpr WeaponFact FINAL_WEAPON[] = {
  { 0, 150000, 0, 333, -1, 93750, 75000, 56250, 1 },
  { 1, 0, 1, 100, 0, 35000, 26250, 0, 0 },
  { 2, 100000, 0, 150, -1, 25000, 50000, 25000, 0 },
};
constexpr int FINAL_WEAPON_COUNT = sizeof(FINAL_WEAPON)/sizeof(FINAL_WEAPON[0]);

// --- expected reconstructed client-view hash checkpoints + whole-session digest ---
struct Checkpoint { unsigned tick; const char* hash; };
constexpr Checkpoint CHECKPOINTS[] = {
  { 1u, "417e518b4c20787ec3512129172dbb79f35287381ac60384475e77505843c390" },
  { 50u, "80b1ee651007577178fb14a995575b0f16a6fcef821c616503964531d0104bbf" },
  { 100u, "684c7a14717c3f4a54d44d8f031ec397de2e11520cc02b7de192bcef05f40698" },
  { 150u, "3f93f728fb3fd1537f43b5e8b1df62cdaa75a146ac707d47eea44bdeb264a665" },
  { 200u, "11d24e63dd31b88ff3f4db5c4327cf80227daa802641dbddb0d99fc590cd4c45" },
};
constexpr int CHECKPOINT_COUNT = sizeof(CHECKPOINTS)/sizeof(CHECKPOINTS[0]);

constexpr const char* SEQUENCE_DIGEST = "f67368e93b82379b7d2ab0d0ab786dce6a529bce0e7165f3594284419336aa2e";

}} // namespace seads::sess_vec
