// AUTO-GENERATED by tools/gen_coeffs.py from tools/detmath_ref.py — DO NOT EDIT.
// Bit-identical hex-float constants shared by the Python reference and C++ kernel.
#pragma once
namespace seads { namespace detm {
constexpr double PI = 0x1.921fb54442d18p+1;
constexpr double HALF_PI = 0x1.921fb54442d18p+0;
constexpr double TWO_PI = 0x1.921fb54442d18p+2;
constexpr double TWO_OVER_PI = 0x1.45f306dc9c883p-1;
constexpr double PIO2_HI = 0x1.921fb54442d18p+0;
constexpr double PIO2_LO = 0x1.1a62633145c07p-54;
constexpr double S1 = -0x1.5555555555549p-3;
constexpr double S2 = 0x1.111111110f8a6p-7;
constexpr double S3 = -0x1.a01a019c161d5p-13;
constexpr double S4 = 0x1.71de357b1fe7dp-19;
constexpr double S5 = -0x1.ae5e68a2b9cebp-26;
constexpr double S6 = 0x1.5d93a5acfd57cp-33;
constexpr double C1 = 0x1.555555555554cp-5;
constexpr double C2 = -0x1.6c16c16c15177p-10;
constexpr double C3 = 0x1.a01a019cb1590p-16;
constexpr double C4 = -0x1.27e4f809c52adp-22;
constexpr double C5 = 0x1.1ee9ebdb4b1c4p-29;
constexpr double C6 = -0x1.8fae9be8838d4p-37;
constexpr double AT[11] = {
    0x1.555555555550dp-2, -0x1.999999998ebc4p-3, 0x1.24924920083ffp-3, -0x1.c71c6fe231671p-4, 0x1.745cdc54c206ep-4, -0x1.3b0f2af749a6dp-4, 0x1.10d66a0d03d51p-4, -0x1.dde2d52defd9ap-5, 0x1.97b4b24760debp-5, -0x1.2b4442c6a6c2fp-5, 0x1.0ad3ae322da11p-6
};
constexpr double ATANHI[4] = {
    0x1.dac670561bb4fp-2, 0x1.921fb54442d18p-1, 0x1.f730bd281f69bp-1, 0x1.921fb54442d18p+0
};
constexpr double ATANLO[4] = {
    0x1.a2b7f222f65e2p-56, 0x1.1a62633145c07p-55, 0x1.007887af0cbbdp-56, 0x1.1a62633145c07p-54
};
}} // namespace seads::detm
