#!/usr/bin/env python3
"""
gen_geo001_vectors.py — emit src/net/geo001_vectors.h from the GEO-001 reference.

Cross-impl parity vectors for the wire codec. The C++ test (src/net/geo001_test_main.cpp)
asserts, for every vector:
  * ENCODE parity — C++ encode(input) == these exact wire bytes (byte-identical wire), and
  * DECODE round-trip — C++ decode(wire) == input.
Because the wire bytes here are produced by tools/geo001_ref.py, encoder agreement is
proven byte-for-byte (C++ == reference), exactly as det_math is proven against detmath_ref.

Reproducibility (so CI `--check` on Linux matches the committed header):
  * i64 / GeoPoint vectors are INTEGER-driven (SplitMix64 integer PRNG + structured
    boundary rows) — no floats enter the wire, so the bytes are identical on every platform.
  * quantize vectors emit `value` as an exact hex-float literal and `scale` as an integer;
    C++ recomputes value*scale (the identical IEEE double op) so `expected` matches without
    the float ever being re-parsed from decimal.

Usage:  python tools/gen_geo001_vectors.py [--check]
"""
import argparse, sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import geo001_ref as g

ROOT = Path(__file__).resolve().parent.parent
HEADER = ROOT / "src" / "net" / "geo001_vectors.h"

N_RANDOM = 256
MASK64 = (1 << 64) - 1
I64_MIN = -(1 << 63)
I64_MAX = (1 << 63) - 1


# SplitMix64 — fully integer PRNG (same construction as gen_detmath_vectors).
class Rng:
    def __init__(self, seed):
        self.s = seed & MASK64

    def next_u64(self):
        self.s = (self.s + 0x9E3779B97F4A7C15) & MASK64
        z = self.s
        z = ((z ^ (z >> 30)) * 0xBF58476D1CE4E5B9) & MASK64
        z = ((z ^ (z >> 27)) * 0x94D049BB133111EB) & MASK64
        return (z ^ (z >> 31)) & MASK64

    def i64_in(self, lo, hi):
        span = hi - lo + 1
        return lo + (self.next_u64() % span)


def hx(v):
    return float.hex(float(v))


def i64lit(v):
    # INT64_MIN can't be written as a literal (-9223372036854775808 parses as negation
    # of an out-of-range positive literal). Emit it as (min+1 - 1).
    if v == I64_MIN:
        return "(-9223372036854775807LL - 1LL)"
    return f"{v}LL"


def bytes_literal(b):
    # fixed-size wire[N] initializer: emit the used bytes; C++ zero-fills the rest.
    return "{" + ",".join("0x%02x" % x for x in b) + "}"


def i64_inputs():
    """Boundary i64 values + LEB128 length edges + seeded random rows."""
    pts = []
    # zero / small signed
    pts += [0, 1, -1, 2, -2, 63, 64, -64, 127, -127, 128, -128]
    # LEB128 length boundaries (after ZigZag): unsigned 2^(7k) edges -> map back to signed
    for k in range(1, 10):
        edge = 1 << (7 * k)
        for u in (edge - 1, edge, edge + 1):
            pts.append(g.zigzag_decode(u))      # signed value whose zigzag is near a length edge
    # SEADS field ranges (quantized): lat +-90e7, lon +-180e7, bearing 0..360e6, alt 0..8e6
    pts += [900000000, -900000000, 1800000000, -1800000000,
            360000000, 8000000, -8000000, 250000000]
    # i64 extremes (ZigZag must handle INT64_MIN)
    pts += [I64_MIN, I64_MAX, I64_MIN + 1, I64_MAX - 1]
    # seeded random across magnitudes
    rng = Rng(0x6E0010001)
    ranges = [(-128, 128), (-1 << 20, 1 << 20), (-1 << 40, 1 << 40), (I64_MIN, I64_MAX),
              (-1800000000, 1800000000)]
    for i in range(N_RANDOM):
        lo, hi = ranges[i % len(ranges)]
        pts.append(rng.i64_in(lo, hi))
    return pts


def point_inputs():
    """Quantized GeoPoint rows (lat,lon,bearing,alt as i64) — integer-driven."""
    pts = []
    # geographic corners / origin / sealed golden start (0,0)
    pts += [(0, 0, 0, 1000000),
            (900000000, 1800000000, 359999999, 8000000),
            (-900000000, -1800000000, 0, 0),
            (451234567, -1799999999, 359999990, 7999000)]
    rng = Rng(0x6E0020002)
    for _ in range(64):
        pts.append((rng.i64_in(-900000000, 900000000),
                    rng.i64_in(-1800000000, 1800000000),
                    rng.i64_in(0, 360000000),
                    rng.i64_in(0, 8000000)))
    return pts


def quant_inputs():
    """(value, scale, expected_i64) — value emitted as exact hex-float."""
    rows = []
    for value, scale in [(0.0, g.ALT_SCALE), (1.5, 1), (-1.5, 1), (2.5, 1), (-2.5, 1),
                         (45.5, g.LATLON_SCALE), (-45.5, g.LATLON_SCALE),
                         (90.0, g.LATLON_SCALE), (-90.0, g.LATLON_SCALE),
                         (180.0, g.LATLON_SCALE), (123.4567891, g.LATLON_SCALE),
                         (359.999999, g.BEARING_SCALE), (8000.0, g.ALT_SCALE),
                         (0.0009765625, g.ALT_SCALE), (1234.5, g.ALT_SCALE)]:
        rows.append((value, scale, g.quantize(value, scale)))
    return rows


def build():
    L = ["// AUTO-GENERATED by tools/gen_geo001_vectors.py — DO NOT EDIT.",
         "// GEO-001 wire codec parity vectors: C++ geo001 vs tools/geo001_ref.py.",
         "// Each row's wire bytes come from the Python reference; C++ must reproduce them",
         "// byte-for-byte and decode them back to the input.",
         "#pragma once",
         "#include <cstdint>",
         "namespace seads { namespace geo001_vec {",
         ""]

    # --- i64 field vectors ---
    L += ["struct I64Vec { long long value; unsigned char wire[10]; int wire_len; };",
          "constexpr I64Vec I64_VECTORS[] = {"]
    for v in i64_inputs():
        w = g.encode_i64(v)
        L.append(f"  {{ {i64lit(v)}, {bytes_literal(w)}, {len(w)} }},")
    L += ["};",
          "constexpr int I64_VECTOR_COUNT = sizeof(I64_VECTORS)/sizeof(I64_VECTORS[0]);",
          ""]

    # --- GeoPoint vectors (quantized i64 fields -> concatenated wire) ---
    L += ["struct PointVec { long long lat; long long lon; long long bearing; long long alt;",
          "                  unsigned char wire[40]; int wire_len; };",
          "constexpr PointVec POINT_VECTORS[] = {"]
    for lat, lon, bear, alt in point_inputs():
        w = g.encode_i64(lat) + g.encode_i64(lon) + g.encode_i64(bear) + g.encode_i64(alt)
        L.append(f"  {{ {i64lit(lat)}, {i64lit(lon)}, {i64lit(bear)}, {i64lit(alt)}, "
                 f"{bytes_literal(w)}, {len(w)} }},")
    L += ["};",
          "constexpr int POINT_VECTOR_COUNT = sizeof(POINT_VECTORS)/sizeof(POINT_VECTORS[0]);",
          ""]

    # --- quantize vectors (value emitted as exact hex-float literal) ---
    L += ["struct QuantVec { double value; long long scale; long long expected; };",
          "constexpr QuantVec QUANT_VECTORS[] = {"]
    for value, scale, exp in quant_inputs():
        L.append(f"  {{ {hx(value)}, {i64lit(scale)}, {i64lit(exp)} }},")
    L += ["};",
          "constexpr int QUANT_VECTOR_COUNT = sizeof(QUANT_VECTORS)/sizeof(QUANT_VECTORS[0]);",
          "",
          "}} // namespace seads::geo001_vec"]
    return "\n".join(L) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    content = build()
    if args.check:
        cur = HEADER.read_text(encoding="utf-8") if HEADER.exists() else ""
        if cur != content:
            print("FAIL: geo001_vectors.h out of sync (run gen_geo001_vectors.py)")
            sys.exit(1)
        print("PASS: geo001_vectors.h in sync")
        return
    HEADER.parent.mkdir(parents=True, exist_ok=True)
    HEADER.write_text(content, encoding="utf-8")
    n = (content.count("LL, {0x") + content.count("LL, {}")
         + content.count("p+") + content.count("p-"))
    print(f"wrote {HEADER}")


if __name__ == "__main__":
    main()
