#!/usr/bin/env python3
"""
gen_event_vectors.py — emit src/net/event_vectors.h from the event-channel reference.

Cross-impl parity vectors for the reliable combat-EVENT channel (netcode layer 6). The C++ test
(src/net/event_test_main.cpp) reruns the whole server->transport->client event channel over the
SESSION-SK-001 scenario (reused from session_vectors.h — the SAME 3-ship gundemo) and asserts:
  * SERVER LOG — the derived event sequence (each event's six integer fields) equals EXPECTED_EVENTS
    (the P-47's burst walks the A6M2's hp 70 -> 0 over 5 hits + 1 kill), and
  * FULL RECONSTRUCTION — under the scenario's isolated single drops the client's applied journal
    equals the server log exactly, and its EVENT_DIGEST (SHA-256 over the reconstructed log) matches
    (the redundant journal delivers EVERY event bit-for-bit as the Python reference), and
  * KILL — the reconstructed kill event (precise tick + final hp) matches, and
  * BLACKOUT (the reliability bound, cross-impl) — with a K-consecutive drop blackout the client
    recovers exactly BLACKOUT_APPLIED_SEQS (the aged-out early hits are permanently lost, the channel
    resyncs and still delivers the kill) and its BLACKOUT_DIGEST matches, and
  * ACCOUNTING — windows emitted / delivered match.

Reuses sess_vec::SCENARIO (session_vectors.h) so the scenario has a SINGLE source of truth. Expected
values come from the deterministic Python reference (tools/event_ref.py), so the header is
byte-identical on every platform and CI `--check` stays green. The event channel rides seal v1.12r0
(it composes the EXISTING protocol-4 session — see event_ref.py; NOT a golden/seal).

Usage:  python tools/gen_event_vectors.py [--check]
"""
import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import event_ref as ev
import session_ref as sr
import ref_kernel as rk
from gen_session_vectors import hx   # hex-float emission (single source with session vectors)

ROOT = Path(__file__).resolve().parent.parent
HEADER = ROOT / "src" / "net" / "event_vectors.h"

# A K-consecutive-frame blackout used as the cross-impl reliability-bound vector: it covers the whole
# in-window lifetime of the two earliest hits (seq 0,1 ride only emits 40/45/50), so those are
# permanently lost while the journal resyncs and still delivers seq 2..5 (incl. the kill).
BLACKOUT_DROPS = [40, 45, 50]


def _emit_event_rows(events):
    rows = []
    for e in events:
        rows.append(f"  {{ {e.seq}, {e.tick}, {e.target}, {e.damage_milli}, "
                    f"{e.hp_after_milli}, {e.killed}, {e.attacker} }},")
    return rows


def build():
    scenario = sr.SESSION

    res = ev.run_events(scenario)                 # standard drops: full reconstruction
    events = res["events"]
    applied = res["applied"]
    assert [e.seq for e in applied] == [e.seq for e in events], "reference not fully reconstructed"
    digest = ev.event_digest(applied)

    kev = ev.kill_event(events)
    kill_index = next(i for i, e in enumerate(events) if e.killed)

    resb = ev.run_events(scenario, drop_emit_ticks=BLACKOUT_DROPS)
    blackout_seqs = [e.seq for e in resb["applied"]]
    blackout_digest = ev.event_digest(resb["applied"])

    L = [
        "// AUTO-GENERATED by tools/gen_event_vectors.py — DO NOT EDIT.",
        "// Reliable combat-EVENT channel (netcode layer 6) parity vectors: C++ harness vs",
        "// tools/event_ref.py. Reuses the SESSION-SK-001 scenario (sess_vec::SCENARIO). Expected",
        "// server event log + full-reconstruction digest + the kill + a K-consecutive-blackout",
        "// reliability-bound vector + transport accounting.",
        "#pragma once",
        "#include <cstdint>",
        '#include "event.h"            // seads::event::{Event, EVENT_WINDOW_K}',
        '#include "session_vectors.h"  // reuse sess_vec::SCENARIO (SESSION-SK-001)',
        "namespace seads { namespace event_vec {",
        "",
        f"constexpr int WINDOW_K = {ev.EVENT_WINDOW_K};   // must equal seads::event::EVENT_WINDOW_K",
        "",
        "// --- server-derived authoritative event log (seq, tick, target, damage_milli, "
        "hp_after_milli, killed, attacker) ---",
        "struct ExpectEvent { std::int64_t seq, tick, target, damage_milli, hp_after_milli, killed,"
        " attacker; };",
        "constexpr ExpectEvent EXPECTED_EVENTS[] = {",
    ]
    L += _emit_event_rows(events)
    L += [
        "};",
        "constexpr int EXPECTED_EVENT_COUNT = sizeof(EXPECTED_EVENTS)/sizeof(EXPECTED_EVENTS[0]);",
        f"constexpr int KILL_INDEX = {kill_index};   // index of the killed==1 event in EXPECTED_EVENTS",
        "",
        "// --- transport accounting (event windows emitted by the server / received by the client) ---",
        f"constexpr unsigned N_WINDOWS = {int(res['n_windows'])}u;",
        f"constexpr unsigned DELIVERED = {int(res['delivered'])}u;",
        "",
        "// --- full-reconstruction digest (SHA-256 over the client's applied event log) ---",
        f'constexpr const char* EVENT_DIGEST = "{digest}";',
        "",
        "// --- reliability-bound vector: a K-consecutive-frame blackout (aged-out early hits lost, ",
        "//     journal resyncs, kill still delivered) — the client recovers exactly these seqs ---",
        f"constexpr std::int64_t BLACKOUT_DROPS[] = {{ {', '.join(str(d) for d in BLACKOUT_DROPS)} }};",
        f"constexpr unsigned BLACKOUT_N_DROPS = {len(BLACKOUT_DROPS)}u;",
        f"constexpr std::int64_t BLACKOUT_APPLIED_SEQS[] = "
        f"{{ {', '.join(str(s) for s in blackout_seqs)} }};",
        f"constexpr int BLACKOUT_APPLIED_COUNT = {len(blackout_seqs)};",
        f'constexpr const char* BLACKOUT_DIGEST = "{blackout_digest}";',
        "",
    ]
    L += _build_multihit()
    L += [
        "}} // namespace seads::event_vec",
    ]
    return "\n".join(L) + "\n"


def _build_multihit():
    """Emit the EVENT-MULTIHIT-001 per-round GRANULARITY vector (see event_ref.MULTIHIT): twin
    P-47Ds land both rounds of every volley on the same tick against one A6M2 -> each volley is TWO
    attributed events (the pre-hit-queue hp-delta derivation lumped them into one, credited to the
    last writer), and the kill volley shows the overkill clamp. Reuses the sess_vec envelope
    constants (same envmod source, baked identically)."""
    sc = ev.MULTIHIT
    res = ev.run_events(sc)
    events = res["events"]
    applied = res["applied"]
    assert [e.seq for e in applied] == [e.seq for e in events], "multihit not fully reconstructed"
    digest = ev.event_digest(applied)
    kill_index = next(i for i, e in enumerate(events) if e.killed)

    env_ref = {"p47d": "sess_vec::ENV_P47D", "a6m2": "sess_vec::ENV_A6M2"}
    L = [
        "// --- EVENT-MULTIHIT-001: the per-round GRANULARITY scenario (twin shooters, one target;",
        "//     every volley = two rounds on the SAME tick -> two attributed events; the kill volley",
        "//     shows the overkill clamp). Envelopes reused from sess_vec (identical bake). ---",
    ]
    for i, ac in enumerate(sc["aircraft"]):
        L.append(f"constexpr session::Phase MH_SCHED_{i}[] = {{")
        for ph in ac["schedule"]:
            L.append(f"  {{{int(ph['start_tick'])}u, {hx(rk.deg2rad(ph['bank_deg']))}, "
                     f"{hx(ph['g_cmd'])}, {hx(ph.get('throttle', 0.0))}, "
                     f"{'true' if ph.get('fire', False) else 'false'}}},")
        L.append("};")
    L.append("constexpr session::AircraftSpec MH_AIRCRAFT[] = {")
    for i, ac in enumerate(sc["aircraft"]):
        s = ac["start"]
        L.append(
            f"  {{ &{env_ref[ac['envelope']]}, {hx(rk.deg2rad(s['lat_deg']))}, "
            f"{hx(rk.deg2rad(s['lon_deg']))}, {hx(rk.deg2rad(s['psi_deg']))}, "
            f"{hx(rk.deg2rad(s['phi_deg']))}, {hx(s['alt_m'])}, {hx(s['tas_mps'])}, "
            f"MH_SCHED_{i}, {len(ac['schedule'])}u }},")
    drops = ", ".join(str(int(d)) for d in sc["drop_emit_ticks"])
    L += [
        "};",
        f"constexpr std::int64_t MH_DROP_EMIT_TICKS[] = {{ {drops} }};",
        "constexpr session::Scenario MH_SCENARIO = {",
        f"  MH_AIRCRAFT, {len(sc['aircraft'])}u, {int(sc['ticks'])}u, {int(sc['snap_every'])}u, "
        f"{int(sc['lag_ticks'])}u, {int(sc['render_delay'])}u,",
        f"  MH_DROP_EMIT_TICKS, {len(sc['drop_emit_ticks'])}u",
        "};",
        "",
        "constexpr ExpectEvent MH_EXPECTED_EVENTS[] = {",
    ]
    L += _emit_event_rows(events)
    L += [
        "};",
        "constexpr int MH_EXPECTED_EVENT_COUNT = "
        "sizeof(MH_EXPECTED_EVENTS)/sizeof(MH_EXPECTED_EVENTS[0]);",
        f"constexpr int MH_KILL_INDEX = {kill_index};",
        f"constexpr unsigned MH_N_WINDOWS = {int(res['n_windows'])}u;",
        f"constexpr unsigned MH_DELIVERED = {int(res['delivered'])}u;",
        f'constexpr const char* MH_EVENT_DIGEST = "{digest}";',
        "",
    ]
    return L


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="fail if header is out of sync")
    args = ap.parse_args()
    content = build()
    if args.check:
        cur = HEADER.read_text(encoding="utf-8") if HEADER.exists() else ""
        if cur != content:
            print("FAIL: event_vectors.h out of sync (run gen_event_vectors.py)")
            sys.exit(1)
        print("PASS: event_vectors.h in sync")
        return
    HEADER.parent.mkdir(parents=True, exist_ok=True)
    HEADER.write_text(content, encoding="utf-8")
    print(f"wrote {HEADER}")


if __name__ == "__main__":
    main()
