#!/usr/bin/env python3
"""
gen_detmath_vectors.py — emit src/det_math/detmath_vectors.h from the Python reference.

A fixed table of (input, expected) hex-float pairs. The C++ det_math test asserts
BIT-EXACT equality, catching any drift between the C++ port and the canonical reference
before the (slower) golden replay runs.

Usage:  python tools/gen_detmath_vectors.py [--check]
"""
import argparse, sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import detmath_ref as dm

ROOT = Path(__file__).resolve().parent.parent
HEADER = ROOT / "src" / "det_math" / "detmath_vectors.h"

ANGLES = [-6.0, -3.0, -1.5, -0.7853981633974483, -0.3, 0.0, 0.1, 0.5,
          0.7853981633974483, 1.0, 1.5, 2.0, 3.0, 6.0]
UNITS = [-0.9, -0.5, -0.25, 0.0, 0.25, 0.5, 0.75, 0.9, 0.999]
TANS = [-1.3, -0.5, 0.0, 0.3, 0.7, 1.2]
SQRTS = [0.5, 1.0, 2.0, 3.0, 100.0, 15000.0, 1e6]


def hx(v):
    return float.hex(float(v))


def row(name, x, y):
    return f'  {{ "{name}", {hx(x)}, {hx(y)} }},'


def build():
    L = ["// AUTO-GENERATED by tools/gen_detmath_vectors.py — DO NOT EDIT.",
         "#pragma once",
         "namespace seads { namespace detm_vec {",
         "struct Vec { const char* fn; double x; double expected; };",
         "constexpr Vec VECTORS[] = {"]
    for x in ANGLES:
        L.append(row("sin", x, dm.det_sin(x)))
        L.append(row("cos", x, dm.det_cos(x)))
        L.append(row("atan", x, dm.det_atan(x)))
    for x in UNITS:
        L.append(row("asin", x, dm.det_asin(x)))
    for x in TANS:
        L.append(row("tan", x, dm.det_tan(x)))
    for x in SQRTS:
        L.append(row("sqrt", x, dm.det_sqrt(x)))
    L.append("};")
    L.append("constexpr int VECTOR_COUNT = sizeof(VECTORS)/sizeof(VECTORS[0]);")
    L.append("}} // namespace seads::detm_vec")
    return "\n".join(L) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    content = build()
    if args.check:
        cur = HEADER.read_text(encoding="utf-8") if HEADER.exists() else ""
        if cur != content:
            print("FAIL: detmath_vectors.h out of sync (run gen_detmath_vectors.py)")
            sys.exit(1)
        print("PASS: detmath_vectors.h in sync")
        return
    HEADER.parent.mkdir(parents=True, exist_ok=True)
    HEADER.write_text(content, encoding="utf-8")
    print(f"wrote {HEADER}")


if __name__ == "__main__":
    main()
