#!/usr/bin/env python3
"""
gen_predict_vectors.py — emit src/net/predict_vectors.h from the prediction reference.

Cross-impl parity vectors for client-side prediction (netcode layer 4b). The C++ test
(src/net/predict_test_main.cpp) reproduces the predictor + reconcile loop over this exact
scripted scenario and asserts:
  * SEQUENCE_DIGEST — SHA-256 over the nominal (seamless) per-tick predicted world_hashes
    equals this value (every tick's canonical predicted snapshot matches the Python reference
    bit-for-bit), and
  * CHECKPOINTS — the predicted hash at selected ticks equals these (readable localization), and
  * HEAL_TICK — a state-desynced predictor (perturbed initial alt) reconciles back EXACTLY at
    this tick and stays in sync thereafter (proves reconcile's snap+replay is load-bearing).

Self-contained + byte-reproducible like gen_lockstep_vectors: the scenario (envelope, start
state, schedule, snapshot cadence, latency, perturbation) is emitted as exact hex-float literals
and integers, so the C++ kernel reproduces identical IEEE doubles -> identical det_math
trajectory -> identical hashes. Expected hashes come from the deterministic Python reference, so
the header is byte-identical on every platform and CI `--check` stays green. The prediction
scenario rides seal v1.4r0 (it is NOT a golden/seal — see predict_ref.py).

Usage:  python tools/gen_predict_vectors.py [--check]
"""
import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import predict_ref as pr
import envelopes as envmod

ROOT = Path(__file__).resolve().parent.parent
HEADER = ROOT / "src" / "net" / "predict_vectors.h"


def hx(v):
    return float.hex(float(v))


def cpp_ident(name):
    return "".join(c.upper() if c.isalnum() else "_" for c in name)


def _lut_literal(field, env):
    xs, ys = env[field]
    sx = ", ".join(hx(v) for v in xs)
    sy = ", ".join(hx(v) for v in ys)
    return f"  /*{field}*/ {{{{{sx}}}, {{{sy}}}}}"


def build():
    sc = pr.SCENARIO
    ticks = int(sc["ticks"])
    name = sc["envelope"]
    env = envmod.load_envelope(name)

    # run the reference: truth states + nominal predicted per-tick hashes + digest + checkpoints
    truth_hashes, truth_states = pr.run_truth()
    nominal = pr.run_predictor(truth_states, reconcile=True, perturb_alt=0.0)
    assert nominal["in_sync"], "nominal predictor must be seamless to seal vectors"
    per_tick = nominal["per_tick"]
    digest = pr.sequence_digest(per_tick)
    cps = pr.checkpoint_ticks(ticks)
    heal_tick = pr.first_heal_tick()

    s = sc["start"]
    L = [
        "// AUTO-GENERATED by tools/gen_predict_vectors.py — DO NOT EDIT.",
        "// Client-side prediction (netcode layer 4b) parity vectors: C++ harness vs",
        "// tools/predict_ref.py. Self-contained scripted scenario + expected predicted",
        "// per-tick world_hash digest/checkpoints + the perturbation heal tick.",
        "#pragma once",
        "#include <cstdint>",
        '#include "flight_types.h"   // seads::Envelope, Command (from the kernel include dir)',
        "namespace seads { namespace pred_vec {",
        "",
        "// --- tuning envelope used by the scenario (deg->rad baked, hex-float, kernel-identical) ---",
        f"constexpr Envelope ENV_{cpp_ident(name)} = {{",
        ",\n".join(_lut_literal(f, env) for f in envmod.LUT_FIELDS) + ",",
        "  " + ", ".join(hx(env[f]) for f in envmod.AERO_FIELDS),
        "};",
        f"constexpr const Envelope* ENVELOPE = &ENV_{cpp_ident(name)};",
        "",
        "// --- own-aircraft initial state (radians / metres / m s^-1) ---",
        "struct Start { double lat, lon, psi, phi, alt, tas; };",
        f"constexpr Start START = {{ {hx(pr.rk.deg2rad(s['lat_deg']))}, "
        f"{hx(pr.rk.deg2rad(s['lon_deg']))}, {hx(pr.rk.deg2rad(s['psi_deg']))}, "
        f"{hx(pr.rk.deg2rad(s['phi_deg']))}, {hx(s['alt_m'])}, {hx(s['tas_mps'])} }};",
        "",
        "// --- command schedule (target_phi in RADIANS, pre-converted; integer phase select) ---",
        "struct Phase { unsigned start_tick; double target_phi; double target_g; double throttle; };",
        "constexpr Phase SCHED[] = {",
    ]
    for ph in sc["schedule"]:
        L.append(f"  {{{int(ph['start_tick'])}u, {hx(pr.rk.deg2rad(ph['bank_deg']))}, "
                 f"{hx(ph['g_cmd'])}, {hx(ph.get('throttle', 0.0))}}},")
    L += [
        "};",
        f"constexpr unsigned N_PHASE    = {len(sc['schedule'])}u;",
        f"constexpr unsigned TICKS      = {ticks}u;",
        f"constexpr unsigned SNAP_EVERY = {int(sc['snap_every'])}u;",
        f"constexpr unsigned LAG_TICKS  = {int(sc['lag_ticks'])}u;",
        f"constexpr double   PERTURB_ALT = {hx(sc['perturb_alt'])};  // negative-control alt desync",
        f"constexpr unsigned HEAL_TICK   = {heal_tick}u;             // perturbed predictor heals here",
        "",
        "// --- expected nominal predicted per-tick hash checkpoints + whole-sequence digest ---",
        "struct Checkpoint { unsigned tick; const char* hash; };",
        "constexpr Checkpoint CHECKPOINTS[] = {",
    ]
    for t in cps:
        L.append(f'  {{ {t}u, "{per_tick[t - 1]}" }},')
    L += [
        "};",
        "constexpr int CHECKPOINT_COUNT = sizeof(CHECKPOINTS)/sizeof(CHECKPOINTS[0]);",
        "",
        f'constexpr const char* SEQUENCE_DIGEST = "{digest}";',
        "",
        "}} // namespace seads::pred_vec",
    ]
    return "\n".join(L) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="fail if header is out of sync")
    args = ap.parse_args()
    content = build()
    if args.check:
        cur = HEADER.read_text(encoding="utf-8") if HEADER.exists() else ""
        if cur != content:
            print("FAIL: predict_vectors.h out of sync (run gen_predict_vectors.py)")
            sys.exit(1)
        print("PASS: predict_vectors.h in sync")
        return
    HEADER.parent.mkdir(parents=True, exist_ok=True)
    HEADER.write_text(content, encoding="utf-8")
    print(f"wrote {HEADER}")


if __name__ == "__main__":
    main()
