#!/usr/bin/env python3
"""
gen_session_vectors.py — emit src/net/session_vectors.h from the session reference.

Cross-impl parity vectors for the server<->client SESSION loop (netcode layer 5). The C++ test
(src/net/session_test_main.cpp) reruns the whole server->transport->client session over this exact
SESSION-SK-001 scenario and asserts:
  * SEQUENCE_DIGEST — SHA-256 over the reconstructed per-tick client-view hashes equals this value
    (the entire dogfight — own predicted ship + interpolated remotes + wire-sourced HP/kills/rounds
    — reconstructs to the identical bytes as the Python reference, bit-for-bit), and
  * CHECKPOINTS — the client-view hash at selected ticks equals these (readable localization), and
  * FINAL_WEAPON — the client's freshest-frame per-aircraft (hp_milli, dead) at the last tick (the
    replicated combat outcome: A6M2 dead, P-47 + Spitfire alive — the KILL crossed the wire), and
  * DELIVERED / N_FRAMES — the transport accounting (emitted vs received under the drop set).

Self-contained + byte-reproducible like gen_predict_vectors: the scenario (3 envelopes, start
states, schedules, cadence, latency, render delay, drop set) is emitted as exact hex-float literals
and integers, so the C++ kernel/predictor reproduce identical IEEE doubles -> identical det_math
trajectory -> identical wire bytes -> identical view hashes. Expected values come from the
deterministic Python reference, so the header is byte-identical on every platform and CI `--check`
stays green. The session rides seal v1.12r0 (it composes the EXISTING protocol-4 wire — see
session_ref.py; NOT a golden/seal).

Usage:  python tools/gen_session_vectors.py [--check]
"""
import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import session_ref as sr
import ref_kernel as rk
import envelopes as envmod

ROOT = Path(__file__).resolve().parent.parent
HEADER = ROOT / "src" / "net" / "session_vectors.h"


def hx(v):
    return float.hex(float(v))


def cpp_ident(name):
    return "".join(c.upper() if c.isalnum() else "_" for c in name)


def _lut_literal(field, env):
    xs, ys = env[field]
    sx = ", ".join(hx(v) for v in xs)
    sy = ", ".join(hx(v) for v in ys)
    return f"  /*{field}*/ {{{{{sx}}}, {{{sy}}}}}"


def _emit_envelope(name):
    env = envmod.load_envelope(name)
    lines = [f"constexpr Envelope ENV_{cpp_ident(name)} = {{",
             ",\n".join(_lut_literal(f, env) for f in envmod.LUT_FIELDS) + ",",
             "  " + ", ".join(hx(env[f]) for f in envmod.AERO_FIELDS),
             "};"]
    return "\n".join(lines)


def build():
    sc = sr.SESSION
    ticks = int(sc["ticks"])

    # run the reference: digest + per-tick view hashes + final weapon facts + delivery accounting
    res = sr.run_session(sc, reconcile=True)
    per_tick = res["per_tick"]
    digest = res["digest"]
    cps = sr.checkpoint_ticks(ticks)
    facts = sr.final_weapon_facts(res["final_wframe"])   # [(id, hp_milli, dead), ...]

    names = [ac["envelope"] for ac in sc["aircraft"]]

    L = [
        "// AUTO-GENERATED by tools/gen_session_vectors.py — DO NOT EDIT.",
        "// Server<->client SESSION loop (netcode layer 5) parity vectors: C++ harness vs",
        "// tools/session_ref.py. Self-contained SESSION-SK-001 scenario (3 aircraft, cadence,",
        "// latency, render delay, packet-loss set) + expected reconstructed client-view digest /",
        "// checkpoints + the replicated final weapon state (the gun kill) + transport accounting.",
        "#pragma once",
        "#include <cstdint>",
        '#include "session.h"   // seads::session::{Phase,AircraftSpec,Scenario}, Envelope, Command',
        "namespace seads { namespace sess_vec {",
        "",
        "// --- tuning envelopes used by the scenario (deg->rad baked, hex-float, kernel-identical) ---",
    ]
    for name in dict.fromkeys(names):   # unique, preserve order (all 3 differ, but be safe)
        L.append(_emit_envelope(name))
    L += [
        "",
        "// --- per-aircraft command schedules (target_phi in RADIANS; integer phase select) ---",
    ]
    for i, ac in enumerate(sc["aircraft"]):
        L.append(f"constexpr session::Phase SCHED_{i}[] = {{")
        for ph in ac["schedule"]:
            L.append(f"  {{{int(ph['start_tick'])}u, {hx(rk.deg2rad(ph['bank_deg']))}, "
                     f"{hx(ph['g_cmd'])}, {hx(ph.get('throttle', 0.0))}, "
                     f"{'true' if ph.get('fire', False) else 'false'}}},")
        L.append("};")
    L += [
        "",
        "// --- aircraft specs (envelope + start state radians/metres/m s^-1 + schedule) ---",
        "constexpr session::AircraftSpec AIRCRAFT[] = {",
    ]
    for i, ac in enumerate(sc["aircraft"]):
        s = ac["start"]
        env_id = cpp_ident(ac["envelope"])
        L.append(
            f"  {{ &ENV_{env_id}, {hx(rk.deg2rad(s['lat_deg']))}, {hx(rk.deg2rad(s['lon_deg']))}, "
            f"{hx(rk.deg2rad(s['psi_deg']))}, {hx(rk.deg2rad(s['phi_deg']))}, {hx(s['alt_m'])}, "
            f"{hx(s['tas_mps'])}, SCHED_{i}, {len(ac['schedule'])}u }},")
    drops = ", ".join(str(int(d)) for d in sc["drop_emit_ticks"])
    L += [
        "};",
        f"constexpr unsigned N_AIRCRAFT  = {len(sc['aircraft'])}u;",
        "",
        f"constexpr std::int64_t DROP_EMIT_TICKS[] = {{ {drops} }};",
        f"constexpr unsigned N_DROPS     = {len(sc['drop_emit_ticks'])}u;",
        "",
        f"constexpr unsigned TICKS        = {ticks}u;",
        f"constexpr unsigned SNAP_EVERY   = {int(sc['snap_every'])}u;",
        f"constexpr unsigned LAG_TICKS    = {int(sc['lag_ticks'])}u;",
        f"constexpr unsigned RENDER_DELAY = {int(sc['render_delay'])}u;",
        "",
        "// --- the assembled server-authoritative scenario ---",
        "constexpr session::Scenario SCENARIO = {",
        "  AIRCRAFT, N_AIRCRAFT, TICKS, SNAP_EVERY, LAG_TICKS, RENDER_DELAY,",
        "  DROP_EMIT_TICKS, N_DROPS",
        "};",
        "",
        "// --- transport accounting (frames emitted by the server / received by the client) ---",
        f"constexpr unsigned N_FRAMES  = {int(res['n_frames'])}u;",
        f"constexpr unsigned DELIVERED = {int(res['delivered'])}u;",
        "",
        "// --- replicated final weapon state on the client (id, hp_milli = round(hp*1e3), dead, "
        "ammo = rounds remaining, last_hit_by = attacker index or -1) ---",
        "struct WeaponFact { std::int64_t id; std::int64_t hp_milli; int dead; std::int64_t ammo;"
        " std::int64_t last_hit_by; };",
        "constexpr WeaponFact FINAL_WEAPON[] = {",
    ]
    for (aid, hp_milli, dead, ammo, last_hit_by) in facts:
        L.append(f"  {{ {aid}, {hp_milli}, {dead}, {ammo}, {last_hit_by} }},")
    L += [
        "};",
        "constexpr int FINAL_WEAPON_COUNT = sizeof(FINAL_WEAPON)/sizeof(FINAL_WEAPON[0]);",
        "",
        "// --- expected reconstructed client-view hash checkpoints + whole-session digest ---",
        "struct Checkpoint { unsigned tick; const char* hash; };",
        "constexpr Checkpoint CHECKPOINTS[] = {",
    ]
    for t in cps:
        L.append(f'  {{ {t}u, "{per_tick[t - 1]}" }},')
    L += [
        "};",
        "constexpr int CHECKPOINT_COUNT = sizeof(CHECKPOINTS)/sizeof(CHECKPOINTS[0]);",
        "",
        f'constexpr const char* SEQUENCE_DIGEST = "{digest}";',
        "",
        "}} // namespace seads::sess_vec",
    ]
    return "\n".join(L) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="fail if header is out of sync")
    args = ap.parse_args()
    content = build()
    if args.check:
        cur = HEADER.read_text(encoding="utf-8") if HEADER.exists() else ""
        if cur != content:
            print("FAIL: session_vectors.h out of sync (run gen_session_vectors.py)")
            sys.exit(1)
        print("PASS: session_vectors.h in sync")
        return
    HEADER.parent.mkdir(parents=True, exist_ok=True)
    HEADER.write_text(content, encoding="utf-8")
    print(f"wrote {HEADER}")


if __name__ == "__main__":
    main()
