#!/usr/bin/env python3
"""
gen_coeffs.py — emit src/det_math/detmath_coeffs.h from the canonical Python reference.

Python's float.hex() produces C99/C++17-compatible hex-float literals, so the C++ kernel
gets BIT-IDENTICAL constants to detmath_ref.py with zero hand-copying. Run this whenever
detmath_ref constants change; CI checks the header is in sync.

Usage:  python tools/gen_coeffs.py [--check]
"""
import argparse, sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import detmath_ref as dm

ROOT = Path(__file__).resolve().parent.parent
HEADER = ROOT / "src" / "det_math" / "detmath_coeffs.h"


def hx(v):
    return float.hex(v)


def build():
    L = []
    L.append("// AUTO-GENERATED by tools/gen_coeffs.py from tools/detmath_ref.py — DO NOT EDIT.")
    L.append("// Bit-identical hex-float constants shared by the Python reference and C++ kernel.")
    L.append("#pragma once")
    L.append("namespace seads { namespace detm {")
    scal = {
        "PI": dm.PI, "HALF_PI": dm.HALF_PI, "TWO_PI": dm.TWO_PI,
        "TWO_OVER_PI": dm.TWO_OVER_PI, "PIO2_HI": dm.PIO2_HI, "PIO2_LO": dm.PIO2_LO,
        "S1": dm._S1, "S2": dm._S2, "S3": dm._S3, "S4": dm._S4, "S5": dm._S5, "S6": dm._S6,
        "C1": dm._C1, "C2": dm._C2, "C3": dm._C3, "C4": dm._C4, "C5": dm._C5, "C6": dm._C6,
    }
    for k, v in scal.items():
        L.append(f"constexpr double {k} = {hx(v)};")
    L.append("constexpr double AT[11] = {")
    L.append("    " + ", ".join(hx(v) for v in dm._aT))
    L.append("};")
    L.append("constexpr double ATANHI[4] = {")
    L.append("    " + ", ".join(hx(v) for v in dm._atanhi))
    L.append("};")
    L.append("constexpr double ATANLO[4] = {")
    L.append("    " + ", ".join(hx(v) for v in dm._atanlo))
    L.append("};")
    L.append("}} // namespace seads::detm")
    return "\n".join(L) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="fail if header is out of sync")
    args = ap.parse_args()
    content = build()
    if args.check:
        cur = HEADER.read_text(encoding="utf-8") if HEADER.exists() else ""
        if cur != content:
            print("FAIL: detmath_coeffs.h out of sync with detmath_ref.py (run gen_coeffs.py)")
            sys.exit(1)
        print("PASS: detmath_coeffs.h in sync")
        return
    HEADER.parent.mkdir(parents=True, exist_ok=True)
    HEADER.write_text(content, encoding="utf-8")
    print(f"wrote {HEADER}")


if __name__ == "__main__":
    main()
