#!/usr/bin/env python3
"""
gen_weapon_vectors.py — emit src/net/weapon_vectors.h from the snapshot reference.

Cross-impl parity vectors for the WEAPON-001 section of the GEO-001 snapshot framing
(protocol 5 since v1.14r0 added the G4 magazine `ammo`; WEAPON-001 first sealed at v1.12r0). The
C++ test (src/net/weapon_test_main.cpp) asserts, per vector:
  * ENCODE parity — C++ encode_snapshot(snap) == these exact wire bytes (full GEO+KIN+WEAPON
    frame), and
  * DECODE round-trip — C++ decode_snapshot(wire) reproduces the per-aircraft hp/fire_cd/ammo
    within one quantum AND every live projectile (position/damage within a quantum; ttl/owner EXACT).

Reproducibility: degree/kernel-unit fields are emitted as exact hex-float literals and
ids/tick/ttl/owner as integers, so C++ quantizes the identical IEEE doubles -> identical wire
bytes; the header is byte-reproducible on every platform (CI `--check` stays green).

Usage:  python tools/gen_weapon_vectors.py [--check]
"""
import argparse, sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import geo001_ref as g
import snapshot_ref as s

ROOT = Path(__file__).resolve().parent.parent
HEADER = ROOT / "src" / "net" / "weapon_vectors.h"


def hx(v):
    return float.hex(float(v))


def i64lit(v):
    if v == -(1 << 63):
        return "(-9223372036854775807LL - 1LL)"
    return f"{v}LL"


def bytes_literal(b):
    return "{" + ",".join("0x%02x" % x for x in b) + "}"


E = s.EntityState
P = s.ProjectileState


# Weapon-bearing snapshots (protocol 6). Entity fields in DEGREES (GEO) + KIN units + WEAPON
# units (hp/fire_cd/ammo/last_hit_by). Projectile fields in DEGREES + damage + integer ttl/owner.
# Cases exercise: the empty world (weapon section = projectile count 0), the golden start (full hp +
# full mag, never hit = last_hit_by -1), a mixed furball (P-47 hp150/ammo337 never hit vs a
# glass-cannon A6M2 hp70/ammo100 last hit by #1 + a DEAD hp0/Winchester(ammo0) corpse KILLED by #2,
# so last_hit_by carries -1/1/2 incl. the ZigZag-signed -1, with rounds carrying distinct
# damage/ttl/owner and antimeridian / ceiling extremes), and the full 8-aircraft roster with varied
# magazines + attackers + a dense round cloud (multi-byte LEB128 in every field).
def weapon_inputs():
    return [
        (0, [], []),                                                   # empty world
        (1, [E(1, 0.0, 0.0, 45.0, 1000.0, 0.0, 250.0, 0.0, 150.0, 0.0, 340.0, -1.0)], []),  # golden start, never hit
        (52000,
         [E(1, 12.3456789, -98.7654321, 359.999999, 7999.999, 39.999999, 175.25, 12.5, 150.0, 3.0, 337.0, -1.0),  # never hit
          E(2, -45.5, 180.0, 0.0, 0.0, -60.5, 0.0, -8.25, 70.0, 9.0, 100.0, 1.0),   # last hit by #1
          E(7, 89.9999999, -179.9999999, 270.0, 8000.0, 0.000001, 305.999, 0.000001, 0.0, 0.0, 0.0, 2.0)],  # dead, killed by #2
         [P(1000, 12.34, -98.76, 0.123456, 7995.5, 12.0, 248, 0),
          P(1001, -45.4, 179.999, 359.0, 50.0, 40.0, 5, 1),
          P(1002, 0.0, 0.0, 180.0, 4000.0, 30.5, 1, 4)]),
        (100000,
         [E(i, (i * 7) % 90, (i * 13) % 180 - 90, (i * 11) % 360, (i * 137) % 8000,
            (i * 17) % 80 - 40, (i * 29) % 320, (i * 19) % 60 - 30,
            (i * 23) % 160, (i * 5) % 12, (i * 43) % 400, (i % 4) - 1)   # last_hit_by cycles -1,0,1,2
          for i in range(1, 9)],
         [P(2000 + j, (j * 9) % 90 - 45, (j * 31) % 360 - 180, (j * 7) % 360, (j * 211) % 8000,
            (j * 3) % 45 + 5, (j * 53) % 250 + 1, j % 8)
          for j in range(0, 12)]),
    ]


def build():
    L = ["// AUTO-GENERATED by tools/gen_weapon_vectors.py — DO NOT EDIT.",
         "// WEAPON-001 snapshot section parity vectors: C++ netsnap vs tools/snapshot_ref.py.",
         "#pragma once",
         "#include <cstdint>",
         "namespace seads { namespace weap_vec {",
         "",
         "struct WEntity { long long id; double lat_deg; double lon_deg; double bearing_deg;",
         "                 double alt_m; double phi_deg; double tas_mps; double gamma_deg;",
         "                 double hp; double fire_cd; double ammo; double last_hit_by; };",
         "struct WProj { long long id; double lat_deg; double lon_deg; double bearing_deg;",
         "               double alt_m; double damage; long long ttl; long long owner; };",
         ""]

    snaps = weapon_inputs()
    for idx, (tick, ents, projs) in enumerate(snaps):
        if ents:
            L.append(f"constexpr WEntity W{idx}_ENTS[] = {{")
            for e in ents:
                L.append(f"  {{ {i64lit(e.id)}, {hx(e.lat_deg)}, {hx(e.lon_deg)}, "
                         f"{hx(e.bearing_deg)}, {hx(e.alt_m)}, {hx(e.phi_deg)}, {hx(e.tas_mps)}, "
                         f"{hx(e.gamma_deg)}, {hx(e.hp)}, {hx(e.fire_cd)}, {hx(e.ammo)}, "
                         f"{hx(e.last_hit_by)} }},")
            L.append("};")
        if projs:
            L.append(f"constexpr WProj W{idx}_PROJS[] = {{")
            for p in projs:
                L.append(f"  {{ {i64lit(p.id)}, {hx(p.lat_deg)}, {hx(p.lon_deg)}, "
                         f"{hx(p.bearing_deg)}, {hx(p.alt_m)}, {hx(p.damage)}, "
                         f"{i64lit(p.ttl)}, {i64lit(p.owner)} }},")
            L.append("};")
        wire = s.encode_snapshot(s.Snapshot(tick, ents, projs))
        L.append(f"constexpr unsigned char W{idx}_WIRE[] = {bytes_literal(wire)};")
        L.append("")

    L += ["struct WeapVec { long long protocol; long long server_tick;",
          "                 const WEntity* entities; int n_entities;",
          "                 const WProj* projectiles; int n_projectiles;",
          "                 const unsigned char* wire; int wire_len; };",
          "constexpr WeapVec WEAPON_VECTORS[] = {"]
    for idx, (tick, ents, projs) in enumerate(snaps):
        ents_ref = f"W{idx}_ENTS" if ents else "nullptr"
        projs_ref = f"W{idx}_PROJS" if projs else "nullptr"
        wire = s.encode_snapshot(s.Snapshot(tick, ents, projs))
        L.append(f"  {{ {i64lit(s.SNAPSHOT_PROTOCOL)}, {i64lit(tick)}, {ents_ref}, {len(ents)}, "
                 f"{projs_ref}, {len(projs)}, W{idx}_WIRE, {len(wire)} }},")
    L += ["};",
          "constexpr int WEAPON_VECTOR_COUNT = sizeof(WEAPON_VECTORS)/sizeof(WEAPON_VECTORS[0]);",
          "",
          "}} // namespace seads::weap_vec"]
    return "\n".join(L) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    content = build()
    if args.check:
        cur = HEADER.read_text(encoding="utf-8") if HEADER.exists() else ""
        if cur != content:
            print("FAIL: weapon_vectors.h out of sync (run gen_weapon_vectors.py)")
            sys.exit(1)
        print("PASS: weapon_vectors.h in sync")
        return
    HEADER.parent.mkdir(parents=True, exist_ok=True)
    HEADER.write_text(content, encoding="utf-8")
    print(f"wrote {HEADER}")


if __name__ == "__main__":
    main()
