#!/usr/bin/env python3
"""
gen_lockstep_vectors.py — emit src/net/lockstep_vectors.h from the lockstep reference.

Cross-impl parity vectors for the loopback lockstep harness (netcode layer 3). The C++ test
(src/net/lockstep_test_main.cpp) drives two C++ kernels through this exact scripted timeline and
asserts:
  * SEQUENCE_DIGEST — SHA-256 over the concatenated per-tick world_hashes equals this value
    (the exhaustive cross-impl check: every tick's canonical snapshot matches the Python
    reference bit-for-bit), and
  * CHECKPOINTS — the per-tick hash at selected ticks equals these (readable divergence
    localization).

Self-contained + byte-reproducible: the scenario (envelopes, initial states, schedules) is
emitted as exact hex-float literals and integers, so the C++ kernel reproduces the identical
IEEE doubles -> identical det_math trajectory -> identical hashes. The expected hashes are
computed by the pure-Python reference (deterministic), so the header is byte-identical on every
platform and CI `--check` stays green. The lockstep scenario rides seal v1.3r0 (it is NOT a
golden/seal — see lockstep_ref.py).

Usage:  python tools/gen_lockstep_vectors.py [--check]
"""
import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import lockstep_ref as ls
import envelopes as envmod

ROOT = Path(__file__).resolve().parent.parent
HEADER = ROOT / "src" / "net" / "lockstep_vectors.h"


def hx(v):
    return float.hex(float(v))


def cpp_ident(name):
    return "".join(c.upper() if c.isalnum() else "_" for c in name)


def _lut_literal(field, env):
    xs, ys = env[field]
    sx = ", ".join(hx(v) for v in xs)
    sy = ", ".join(hx(v) for v in ys)
    return f"  /*{field}*/ {{{{{sx}}}, {{{sy}}}}}"


def build():
    scenario = ls.SCENARIO
    ac_list = scenario["aircraft"]
    ticks = int(scenario["ticks"])

    # unique envelope names in first-use order -> a stable index per aircraft
    env_names = []
    for ac in ac_list:
        if ac["envelope"] not in env_names:
            env_names.append(ac["envelope"])

    # run the reference once: per-tick hashes + digest + checkpoints
    r = ls.run_lockstep()
    assert r["in_sync"], "reference scenario must be in sync to seal vectors"
    per_tick = r["per_tick"]
    digest = ls.sequence_digest(per_tick)
    cps = ls.checkpoint_ticks(ticks)

    L = [
        "// AUTO-GENERATED by tools/gen_lockstep_vectors.py — DO NOT EDIT.",
        "// Loopback lockstep (netcode layer 3) parity vectors: C++ harness vs tools/lockstep_ref.py.",
        "// Self-contained scripted timeline + expected per-tick world_hash digest/checkpoints.",
        "#pragma once",
        "#include <cstdint>",
        '#include "flight_types.h"   // seads::Envelope, Command (from the kernel include dir)',
        "namespace seads { namespace ls_vec {",
        "",
        "// --- tuning envelopes used by the scenario (deg->rad baked, hex-float, kernel-identical) ---",
    ]

    for name in env_names:
        env = envmod.load_envelope(name)
        L.append(f"constexpr Envelope ENV_{cpp_ident(name)} = {{")
        L.append(",\n".join(_lut_literal(f, env) for f in envmod.LUT_FIELDS) + ",")
        L.append("  " + ", ".join(hx(env[f]) for f in envmod.AERO_FIELDS))
        L.append("};")
    L.append("constexpr const Envelope* ENVELOPES[] = {")
    L.append("    " + ", ".join(f"&ENV_{cpp_ident(n)}" for n in env_names))
    L.append("};")
    L.append("")

    # --- per-aircraft command schedules (target_phi in RADIANS, pre-converted) ---
    L += ["struct Phase  { unsigned start_tick; double target_phi; double target_g; double throttle; };",
          "struct AcSpec { double lat, lon, psi, phi, alt, tas; int env_idx;",
          "                const Phase* sched; unsigned n_phase; };",
          ""]
    for ai, ac in enumerate(ac_list):
        L.append(f"constexpr Phase AC{ai}_SCHED[] = {{")
        for ph in ac["schedule"]:
            L.append(f"  {{{int(ph['start_tick'])}u, {hx(ls.rk.deg2rad(ph['bank_deg']))}, "
                     f"{hx(ph['g_cmd'])}, {hx(ph.get('throttle', 0.0))}}},")
        L.append("};")

    L.append("constexpr AcSpec AIRCRAFT[] = {")
    for ai, ac in enumerate(ac_list):
        s = ac["start"]
        env_idx = env_names.index(ac["envelope"])
        L.append(f"  {{ {hx(ls.rk.deg2rad(s['lat_deg']))}, {hx(ls.rk.deg2rad(s['lon_deg']))}, "
                 f"{hx(ls.rk.deg2rad(s['psi_deg']))}, {hx(ls.rk.deg2rad(s['phi_deg']))}, "
                 f"{hx(s['alt_m'])}, {hx(s['tas_mps'])}, {env_idx}, AC{ai}_SCHED, "
                 f"{len(ac['schedule'])}u }},")
    L.append("};")
    L.append(f"constexpr unsigned N_AIRCRAFT = {len(ac_list)}u;")
    L.append(f"constexpr unsigned TICKS      = {ticks}u;")
    L.append("")

    # --- expected per-tick hash checkpoints + whole-sequence digest ---
    L += ["struct Checkpoint { unsigned tick; const char* hash; };",
          "constexpr Checkpoint CHECKPOINTS[] = {"]
    for t in cps:
        L.append(f'  {{ {t}u, "{per_tick[t - 1]}" }},')
    L += ["};",
          "constexpr int CHECKPOINT_COUNT = sizeof(CHECKPOINTS)/sizeof(CHECKPOINTS[0]);",
          "",
          f'constexpr const char* SEQUENCE_DIGEST = "{digest}";',
          "",
          "}} // namespace seads::ls_vec"]
    return "\n".join(L) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="fail if header is out of sync")
    args = ap.parse_args()
    content = build()
    if args.check:
        cur = HEADER.read_text(encoding="utf-8") if HEADER.exists() else ""
        if cur != content:
            print("FAIL: lockstep_vectors.h out of sync (run gen_lockstep_vectors.py)")
            sys.exit(1)
        print("PASS: lockstep_vectors.h in sync")
        return
    HEADER.parent.mkdir(parents=True, exist_ok=True)
    HEADER.write_text(content, encoding="utf-8")
    print(f"wrote {HEADER}")


if __name__ == "__main__":
    main()
