#!/usr/bin/env python3
"""
gen_golden_params.py — emit src/kernel/golden_params.h from config/rails/atm.json.

Rails/golden scalars are emitted as exact hex-float literals so the C++ golden runner
uses BIT-IDENTICAL inputs to the Python reference. Run after editing atm.json; CI checks
sync with --check.

Usage:  python tools/gen_golden_params.py [--check]
"""
import argparse, json, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
HEADER = ROOT / "src" / "kernel" / "golden_params.h"


def hx(v):
    return float.hex(float(v))


def build():
    rails = json.loads((ROOT / "config/rails/atm.json").read_text(encoding="utf-8"))
    r = rails["rails"]
    g = rails["golden"]
    L = [
        "// AUTO-GENERATED by tools/gen_golden_params.py from config/rails/atm.json — DO NOT EDIT.",
        "#pragma once",
        "namespace seads { namespace golden {",
        f"constexpr double R_M        = {hx(r['geometry']['radius_m'])};",
        f"constexpr double DT_S       = {hx(r['dt_s'])};",
        f"constexpr double G0         = {hx(r['gravity_mps2'])};",
        f"constexpr double ATM_TOP_M  = {hx(r['atm_top_m'])};",
        f"constexpr double SOFT_M     = {hx(r['atm_soft_band_m'])};",
        f"constexpr unsigned TICKS    = {int(g['ticks'])}u;",
        f"constexpr double START_LAT_DEG = {hx(g['start_lat_deg'])};",
        f"constexpr double START_LON_DEG = {hx(g['start_lon_deg'])};",
        f"constexpr double START_PSI_DEG = {hx(g['start_psi_deg'])};",
        f"constexpr double START_PHI_DEG = {hx(g['start_phi_deg'])};",
        f"constexpr double START_ALT_M   = {hx(g['start_alt_m'])};",
        f"constexpr double START_TAS_MPS = {hx(g['start_tas_mps'])};",
        "}} // namespace seads::golden",
    ]
    return "\n".join(L) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    content = build()
    if args.check:
        cur = HEADER.read_text(encoding="utf-8") if HEADER.exists() else ""
        if cur != content:
            print("FAIL: golden_params.h out of sync (run gen_golden_params.py)")
            sys.exit(1)
        print("PASS: golden_params.h in sync")
        return
    HEADER.parent.mkdir(parents=True, exist_ok=True)
    HEADER.write_text(content, encoding="utf-8")
    print(f"wrote {HEADER}")


if __name__ == "__main__":
    main()
