#!/usr/bin/env python3
"""
gen_snapshot_vectors.py — emit src/net/snapshot_vectors.h from the snapshot reference.

Cross-impl parity vectors for the GEO-001 snapshot framing. The C++ test
(src/net/snapshot_test_main.cpp) asserts, per vector:
  * ENCODE parity — C++ encode_snapshot(snap) == these exact wire bytes, and
  * DECODE round-trip — C++ decode_snapshot(wire) reproduces the snapshot fields.
Plus a conversion table proving from_kernel(rad)->quantize is bit-identical to the reference.

Reproducibility: entity degree fields are emitted as exact hex-float literals and ids/tick
as integers, so C++ quantizes the identical IEEE doubles -> identical wire bytes; the header
is byte-reproducible on every platform (CI `--check` stays green).

Usage:  python tools/gen_snapshot_vectors.py [--check]
"""
import argparse, sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import geo001_ref as g
import snapshot_ref as s

ROOT = Path(__file__).resolve().parent.parent
HEADER = ROOT / "src" / "net" / "snapshot_vectors.h"


def hx(v):
    return float.hex(float(v))


def i64lit(v):
    if v == -(1 << 63):
        return "(-9223372036854775807LL - 1LL)"
    return f"{v}LL"


def bytes_literal(b):
    return "{" + ",".join("0x%02x" % x for x in b) + "}"


# Snapshots specified by (server_tick, [entities]) with entity fields in DEGREES (GEO) and
# KIN units (phi deg, tas m/s). Origin (0,0) is the sealed golden start; extremes exercise
# multi-byte LEB128 framing in BOTH the GEO and KIN sections.
def snapshot_inputs():
    E = s.EntityState
    return [
        (0, []),                                                       # empty world
        (1, [E(1, 0.0, 0.0, 45.0, 1000.0, 0.0, 250.0, 0.0)]),          # golden start, wings level
        (12345, [E(1, 12.3456789, -98.7654321, 359.999999, 7999.999, 39.999999, 175.25, 12.5),
                 E(2, -45.5, 180.0, 0.0, 0.0, -60.5, 0.0, -8.25),
                 E(7, 89.9999999, -179.9999999, 270.0, 8000.0, 0.000001, 305.999, 0.000001)]),
        (100000, [E(i, (i * 7) % 90, (i * 13) % 180 - 90, (i * 11) % 360, (i * 137) % 8000,
                    (i * 17) % 80 - 40, (i * 29) % 320, (i * 19) % 60 - 30)
                  for i in range(1, 9)]),                              # full 8-aircraft roster sized
    ]


# Conversion table: kernel radians -> expected quantized i64 for lat/lon/bearing.
def conv_inputs():
    rows = []
    for lat_r, lon_r, psi_r in [(0.0, 0.0, 0.0), (s.PI, 0.0, s.PI / 4.0),
                                (0.5, -1.2, 3.0), (-0.3, 2.9, 6.2),
                                (s.DEG2RAD * 45.0, s.DEG2RAD * -120.0, s.DEG2RAD * 359.0)]:
        e = s.from_kernel(0, lat_r, lon_r, psi_r, 0.0)
        rows.append((lat_r, lon_r, psi_r,
                     g.quantize(e.lat_deg, g.LATLON_SCALE),
                     g.quantize(e.lon_deg, g.LATLON_SCALE),
                     g.quantize(e.bearing_deg, g.BEARING_SCALE)))
    return rows


def build():
    L = ["// AUTO-GENERATED by tools/gen_snapshot_vectors.py — DO NOT EDIT.",
         "// GEO-001 snapshot framing parity vectors: C++ netsnap vs tools/snapshot_ref.py.",
         "#pragma once",
         "#include <cstdint>",
         "namespace seads { namespace snap_vec {",
         "",
         "struct SnapEntity { long long id; double lat_deg; double lon_deg;",
         "                    double bearing_deg; double alt_m; double phi_deg; double tas_mps;",
         "                    double gamma_deg; };",
         ""]

    snaps = snapshot_inputs()
    # per-snapshot entity arrays + wire byte arrays
    for idx, (tick, ents) in enumerate(snaps):
        if ents:
            L.append(f"constexpr SnapEntity SNAP{idx}_ENTS[] = {{")
            for e in ents:
                L.append(f"  {{ {i64lit(e.id)}, {hx(e.lat_deg)}, {hx(e.lon_deg)}, "
                         f"{hx(e.bearing_deg)}, {hx(e.alt_m)}, {hx(e.phi_deg)}, {hx(e.tas_mps)}, "
                         f"{hx(e.gamma_deg)} }},")
            L.append("};")
        snap = s.Snapshot(tick, ents)
        wire = s.encode_snapshot(snap)
        L.append(f"constexpr unsigned char SNAP{idx}_WIRE[] = {bytes_literal(wire)};")
        L.append("")

    L += ["struct SnapVec { long long protocol; long long server_tick;",
          "                 const SnapEntity* entities; int n_entities;",
          "                 const unsigned char* wire; int wire_len; };",
          "constexpr SnapVec SNAP_VECTORS[] = {"]
    for idx, (tick, ents) in enumerate(snaps):
        ents_ref = f"SNAP{idx}_ENTS" if ents else "nullptr"
        wire = s.encode_snapshot(s.Snapshot(tick, ents))
        L.append(f"  {{ {i64lit(s.SNAPSHOT_PROTOCOL)}, {i64lit(tick)}, {ents_ref}, "
                 f"{len(ents)}, SNAP{idx}_WIRE, {len(wire)} }},")
    L += ["};",
          "constexpr int SNAP_VECTOR_COUNT = sizeof(SNAP_VECTORS)/sizeof(SNAP_VECTORS[0]);",
          ""]

    # conversion vectors
    L += ["struct ConvVec { double lat_rad; double lon_rad; double psi_rad;",
          "                 long long lat_q; long long lon_q; long long bear_q; };",
          "constexpr ConvVec CONV_VECTORS[] = {"]
    for lat_r, lon_r, psi_r, latq, lonq, bearq in conv_inputs():
        L.append(f"  {{ {hx(lat_r)}, {hx(lon_r)}, {hx(psi_r)}, "
                 f"{i64lit(latq)}, {i64lit(lonq)}, {i64lit(bearq)} }},")
    L += ["};",
          "constexpr int CONV_VECTOR_COUNT = sizeof(CONV_VECTORS)/sizeof(CONV_VECTORS[0]);",
          "",
          "}} // namespace seads::snap_vec"]
    return "\n".join(L) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    content = build()
    if args.check:
        cur = HEADER.read_text(encoding="utf-8") if HEADER.exists() else ""
        if cur != content:
            print("FAIL: snapshot_vectors.h out of sync (run gen_snapshot_vectors.py)")
            sys.exit(1)
        print("PASS: snapshot_vectors.h in sync")
        return
    HEADER.parent.mkdir(parents=True, exist_ok=True)
    HEADER.write_text(content, encoding="utf-8")
    print(f"wrote {HEADER}")


if __name__ == "__main__":
    main()
