#!/usr/bin/env python3
"""
gen_scenario_params.py — emit src/kernel/scenario_params.h from config/scenarios/*.json.

For each scenario, emits the scripted-timeline inputs as exact hex-float / u32 literals so the
C++ scenario runner (seads_scenario) drives BIT-IDENTICAL inputs to tools/ref_kernel.py:
  * start state angles are pre-converted to radians via the same deg2rad as the reference,
  * scheduled bank targets are pre-converted to radians, g_cmd (load factor) is dimensionless,
  * envelopes are referenced as &envtab::<NAME> from the generated envelope_tables.h.
CI checks sync with --check.

Usage:  python tools/gen_scenario_params.py [--check]
"""
import argparse, json, sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import envelopes as envmod

ROOT = Path(__file__).resolve().parent.parent
HEADER = ROOT / "src" / "kernel" / "scenario_params.h"
SCEN_DIR = ROOT / "config" / "scenarios"


def sym(s):
    return "".join(c.upper() if c.isalnum() else "_" for c in s)


def hx(v):
    return float.hex(float(v))


def deg2rad(d):
    return envmod.deg2rad(float(d))   # d * (PI/180.0), matches ref_kernel.deg2rad


def build():
    scenarios = []
    for p in sorted(SCEN_DIR.glob("*.json")):
        scenarios.append(json.loads(p.read_text(encoding="utf-8")))

    L = [
        "// AUTO-GENERATED by tools/gen_scenario_params.py from config/scenarios/ — DO NOT EDIT.",
        "// Scripted-timeline inputs (hex-float radians / u32 ticks) bit-identical to ref_kernel.py.",
        "#pragma once",
        '#include "envelope_tables.h"',
        "namespace seads { namespace scen {",
        "struct Phase  { unsigned start_tick; double target_phi; double target_g; double throttle;",
        "                unsigned fire; };  // fire: G1 (v1.9r0) gun trigger (0/1)",
        "struct AcSpec { double lat, lon, psi, phi, alt, tas;",
        "                const Envelope* env; const Phase* sched; unsigned n_phase; };",
        "struct Scenario { const char* id; unsigned ticks; const AcSpec* ac; unsigned n_ac; };",
    ]

    all_syms = []
    for doc in scenarios:
        sid = doc["header"]["id"]
        ssym = sym(sid)
        all_syms.append(ssym)
        # per-aircraft phase arrays
        for ai, ac in enumerate(doc["aircraft"]):
            L.append(f"constexpr Phase {ssym}_AC{ai}_SCHED[] = {{")
            rows = []
            for ph in ac["schedule"]:
                rows.append(f"  {{{int(ph['start_tick'])}u, {hx(deg2rad(ph['bank_deg']))}, "
                            f"{hx(ph['g_cmd'])}, {hx(ph.get('throttle', 0.0))}, "
                            f"{1 if ph.get('fire', False) else 0}u}}")
            L.append(",\n".join(rows))
            L.append("};")
        # aircraft array
        L.append(f"constexpr AcSpec {ssym}_AC[] = {{")
        rows = []
        for ai, ac in enumerate(doc["aircraft"]):
            s = ac["start"]
            env_sym = "".join(c.upper() if c.isalnum() else "_" for c in ac["envelope"])
            rows.append(
                f"  {{ {hx(deg2rad(s['lat_deg']))}, {hx(deg2rad(s['lon_deg']))}, "
                f"{hx(deg2rad(s['psi_deg']))}, {hx(deg2rad(s['phi_deg']))}, "
                f"{hx(s['alt_m'])}, {hx(s['tas_mps'])}, "
                f"&envtab::{env_sym}, {ssym}_AC{ai}_SCHED, {len(ac['schedule'])}u }}")
        L.append(",\n".join(rows))
        L.append("};")
        L.append(f'constexpr Scenario {ssym} = {{ "{sid}", {int(doc["ticks"])}u, '
                 f"{ssym}_AC, {len(doc['aircraft'])}u }};")

    L.append("constexpr const Scenario* ALL[] = {")
    L.append("    " + ", ".join(f"&{s}" for s in all_syms))
    L.append("};")
    L.append(f"constexpr unsigned N_ALL = {len(all_syms)}u;")
    L.append("}} // namespace seads::scen")
    return "\n".join(L) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="fail if header is out of sync")
    args = ap.parse_args()
    content = build()
    if args.check:
        cur = HEADER.read_text(encoding="utf-8") if HEADER.exists() else ""
        if cur != content:
            print("FAIL: scenario_params.h out of sync (run gen_scenario_params.py)")
            sys.exit(1)
        print("PASS: scenario_params.h in sync")
        return
    HEADER.parent.mkdir(parents=True, exist_ok=True)
    HEADER.write_text(content, encoding="utf-8")
    print(f"wrote {HEADER}")


if __name__ == "__main__":
    main()
