#!/usr/bin/env python3
"""
gen_interp_vectors.py — emit src/net/interp_vectors.h from the interpolation reference.

Cross-impl parity vectors for the remote interpolation buffer (netcode layer 4a). The C++ test
(src/net/interp_test_main.cpp) builds each buffer, samples at the given render tick, and asserts
the interpolated entities are BIT-IDENTICAL to these (pure IEEE +,-,*,/ → exact equality, not a
tolerance). Byte-reproducible: all fields are exact hex-float literals / integers, so C++ computes
the identical doubles on every platform and CI `--check` stays green.

Usage:  python tools/gen_interp_vectors.py [--check]
"""
import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import snapshot_ref as s
import interp_ref as ip

ROOT = Path(__file__).resolve().parent.parent
HEADER = ROOT / "src" / "net" / "interp_vectors.h"


def hx(v):
    return float.hex(float(v))


def E(i, lat, lon, bear, alt):
    return s.EntityState(i, lat, lon, bear, alt)


# Each case: (label, [(server_tick, [EntityState...]) ...], render_tick).
def cases():
    return [
        ("midpoint",
         [(0, [E(1, 0.0, 0.0, 10.0, 1000.0)]),
          (10, [E(1, 2.0, -4.0, 50.0, 2000.0)])], 5.0),
        ("quarter",
         [(0, [E(1, 0.0, 0.0, 0.0, 0.0)]),
          (8, [E(1, 8.0, 16.0, 80.0, 4000.0)])], 2.0),
        ("bearing_seam",
         [(100, [E(1, 1.0, 2.0, 350.0, 500.0)]),
          (110, [E(1, 1.0, 2.0, 10.0, 500.0)])], 105.0),
        ("bearing_seam_down",
         [(0, [E(1, 0.0, 0.0, 10.0, 0.0)]),
          (10, [E(1, 0.0, 0.0, 350.0, 0.0)])], 5.0),
        ("lon_antimeridian",
         [(0, [E(1, 5.0, 170.0, 0.0, 0.0)]),
          (10, [E(1, 5.0, -170.0, 0.0, 0.0)])], 5.0),
        ("hold_before_first",
         [(20, [E(1, 5.0, 5.0, 90.0, 100.0)]),
          (30, [E(1, 6.0, 5.0, 90.0, 100.0)])], 10.0),
        ("hold_after_last",
         [(20, [E(1, 5.0, 5.0, 90.0, 100.0)]),
          (30, [E(1, 6.0, 5.0, 90.0, 100.0)])], 99.0),
        ("multi_entity_one_missing",
         [(0, [E(1, 0.0, 0.0, 0.0, 0.0), E(2, 10.0, 10.0, 90.0, 500.0)]),
          (4, [E(1, 4.0, 0.0, 0.0, 0.0)])], 2.0),
        ("three_frames_interior",
         [(0, [E(7, 0.0, 0.0, 0.0, 0.0)]),
          (5, [E(7, 5.0, -5.0, 45.0, 250.0)]),
          (15, [E(7, 5.0, 5.0, 90.0, 750.0)])], 10.0),
        ("realistic_decoded_degrees",
         [(1000, [E(3, 12.3456789, -98.7654321, 270.0, 7999.999),
                  E(5, -45.5, 179.9999999, 0.0, 10.0)]),
          (1005, [E(3, 12.4, -98.7, 272.5, 7999.5),
                  E(5, -45.4, -179.9999999, 359.5, 12.0)])], 1002.5),
    ]


def build():
    L = ["// AUTO-GENERATED by tools/gen_interp_vectors.py — DO NOT EDIT.",
         "// Remote interpolation (netcode layer 4a) parity vectors: C++ seads_net vs tools/interp_ref.py.",
         "#pragma once",
         "#include <cstdint>",
         "namespace seads { namespace interp_vec {",
         "",
         "struct IEnt   { long long id; double lat_deg; double lon_deg;",
         "                double bearing_deg; double alt_m; };",
         "struct IFrame { long long server_tick; const IEnt* ents; int n; };",
         "struct ICase  { const char* label; const IFrame* frames; int n_frames;",
         "                double render_tick; const IEnt* expect; int n_expect; };",
         ""]

    cs = cases()
    for ci, (label, frames, rt) in enumerate(cs):
        # input frames
        for fi, (tick, ents) in enumerate(frames):
            L.append(f"constexpr IEnt C{ci}_F{fi}_ENTS[] = {{")
            for e in ents:
                L.append(f"  {{ {e.id}LL, {hx(e.lat_deg)}, {hx(e.lon_deg)}, "
                         f"{hx(e.bearing_deg)}, {hx(e.alt_m)} }},")
            L.append("};")
        L.append(f"constexpr IFrame C{ci}_FRAMES[] = {{")
        for fi, (tick, ents) in enumerate(frames):
            L.append(f"  {{ {tick}LL, C{ci}_F{fi}_ENTS, {len(ents)} }},")
        L.append("};")
        # expected output (run the reference)
        buf = ip.SnapshotBuffer()
        for tick, ents in frames:
            buf.add(s.Snapshot(tick, ents))
        out = buf.sample(rt)
        L.append(f"constexpr IEnt C{ci}_EXPECT[] = {{")
        for e in out:
            L.append(f"  {{ {e.id}LL, {hx(e.lat_deg)}, {hx(e.lon_deg)}, "
                     f"{hx(e.bearing_deg)}, {hx(e.alt_m)} }},")
        L.append("};")
        L.append("")

    L += ["constexpr ICase CASES[] = {"]
    for ci, (label, frames, rt) in enumerate(cs):
        buf = ip.SnapshotBuffer()
        for tick, ents in frames:
            buf.add(s.Snapshot(tick, ents))
        n_out = len(buf.sample(rt))
        L.append(f'  {{ "{label}", C{ci}_FRAMES, {len(frames)}, {hx(rt)}, '
                 f"C{ci}_EXPECT, {n_out} }},")
    L += ["};",
          "constexpr int CASE_COUNT = sizeof(CASES)/sizeof(CASES[0]);",
          "",
          "}} // namespace seads::interp_vec"]
    return "\n".join(L) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="fail if header is out of sync")
    args = ap.parse_args()
    content = build()
    if args.check:
        cur = HEADER.read_text(encoding="utf-8") if HEADER.exists() else ""
        if cur != content:
            print("FAIL: interp_vectors.h out of sync (run gen_interp_vectors.py)")
            sys.exit(1)
        print("PASS: interp_vectors.h in sync")
        return
    HEADER.parent.mkdir(parents=True, exist_ok=True)
    HEADER.write_text(content, encoding="utf-8")
    print(f"wrote {HEADER}")


if __name__ == "__main__":
    main()
