#!/usr/bin/env python3
"""
gen_detmath_vectors.py — emit src/det_math/detmath_vectors.h from the Python reference.

A table of (fn, x, y, expected) hex-float rows. The C++ det_math test asserts BIT-EXACT
equality against these, catching any drift between the C++ port and the canonical reference
(tools/detmath_ref.py) before the (slower) golden replay runs.

Coverage goal (Step 2): prove C++ == reference bit-for-bit over each function's FULL SEADS
operating domain, not just a handful of points. Each function gets:
  * structured BOUNDARY rows — the algorithm's hinge points (quadrant edges k*pi/2, the
    fdlibm atan region boundaries 7/16..39/16, asin's +/-1 clamp, atan2 axis cases, the
    wrap edges +/-k*2pi and the just-over-pi nudge), plus tiny/large magnitudes; and
  * dense SEEDED random rows over the real argument range (SplitMix64 integer RNG; the
    drawn doubles use only + - * / so the emitted header is byte-reproducible on every
    platform — CI runs this with --check on Linux).

Domains mirror tools/det_math_oracle.py (the accuracy gate). Here tolerance is EXACT
bit-equality: this is parity (C++ vs reference), not the <=2-ULP MPFR accuracy budget.

Determinism notes: no wall-clock RNG, no libm transcendentals are used to pick sample
points (those could differ by 1 ULP across platforms and desync the header). Only integer
math + IEEE +-*/ produce the x/y values; the expected values come from detmath_ref, which
itself uses only +-*/ and correctly-rounded sqrt.

Usage:  python tools/gen_detmath_vectors.py [--check]
"""
import argparse, sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import detmath_ref as dm

ROOT = Path(__file__).resolve().parent.parent
HEADER = ROOT / "src" / "det_math" / "detmath_vectors.h"

# Random rows per function group. Seeded + deterministic; vary the draw by index only.
N_RANDOM = 512

PI = dm.PI
HALF_PI = dm.HALF_PI
TWO_PI = dm.TWO_PI
MASK64 = (1 << 64) - 1


# ----------------------------------------------------------------------------------------
# SplitMix64 — a fully integer PRNG. u01() maps the top 53 bits to [0,1) by multiplying by
# an exact power-of-two reciprocal, so every drawn double is identical on any platform.
class Rng:
    def __init__(self, seed):
        self.s = seed & MASK64

    def next_u64(self):
        self.s = (self.s + 0x9E3779B97F4A7C15) & MASK64
        z = self.s
        z = ((z ^ (z >> 30)) * 0xBF58476D1CE4E5B9) & MASK64
        z = ((z ^ (z >> 27)) * 0x94D049BB133111EB) & MASK64
        return (z ^ (z >> 31)) & MASK64

    def u01(self):
        # 53-bit mantissa / 2^53  ->  exact, reproducible double in [0,1)
        return (self.next_u64() >> 11) * (1.0 / (1 << 53))

    def uniform(self, lo, hi):
        return lo + (hi - lo) * self.u01()

    def pick(self, seq):
        return seq[self.next_u64() % len(seq)]


def hx(v):
    return float.hex(float(v))


# ----------------------------------------------------------------------------------------
class Table:
    """Accumulates (fn, x, y, expected) rows."""
    def __init__(self):
        self.rows = []

    def unary(self, name, fn, x):
        self.rows.append((name, float(x), 0.0, float(fn(x))))

    def binary(self, name, fn, x, y):
        self.rows.append((name, float(x), float(y), float(fn(x, y))))

    def unary_many(self, name, fn, xs):
        for x in xs:
            self.unary(name, fn, x)

    def unary_random(self, name, fn, ranges, rng, n):
        # round-robin across the given linear sub-ranges so every decade is covered
        for i in range(n):
            lo, hi = ranges[i % len(ranges)]
            self.unary(name, fn, rng.uniform(lo, hi))

    def emit(self):
        L = ["// AUTO-GENERATED by tools/gen_detmath_vectors.py — DO NOT EDIT.",
             "// Bit-exact parity vectors: C++ det_math vs the Python reference, over the",
             "// full SEADS domain of each function (boundaries + seeded dense sampling).",
             "#pragma once",
             "namespace seads { namespace detm_vec {",
             "// y is the second operand (atan2 only); 0.0 and unused for unary functions.",
             "struct Vec { const char* fn; double x; double y; double expected; };",
             "constexpr Vec VECTORS[] = {"]
        for name, x, y, e in self.rows:
            L.append(f'  {{ "{name}", {hx(x)}, {hx(y)}, {hx(e)} }},')
        L.append("};")
        L.append("constexpr int VECTOR_COUNT = sizeof(VECTORS)/sizeof(VECTORS[0]);")
        L.append("}} // namespace seads::detm_vec")
        return "\n".join(L) + "\n"


# ----------------------------------------------------------------------------------------
def quadrant_edges():
    """k*pi/2 and small offsets around each — where the Cody-Waite quadrant flips."""
    pts = []
    for k in range(-4, 5):
        c = k * HALF_PI
        pts += [c, c + 1e-9, c - 1e-9, c + 1e-6, c - 1e-6]
    return pts


def build():
    t = Table()

    # --- sin / cos : pre-wrapped angle domain [-2pi, 2pi] (reference's stated assumption) ---
    ang_ranges = [(-TWO_PI, -PI), (-PI, 0.0), (0.0, PI), (PI, TWO_PI)]
    ang_bounds = [0.0, PI / 4, -PI / 4, 1e-12, -1e-12, 2.0 ** -27, -(2.0 ** -27),
                  TWO_PI, -TWO_PI] + quadrant_edges()
    for name, fn in (("sin", dm.det_sin), ("cos", dm.det_cos)):
        t.unary_many(name, fn, ang_bounds)
    t.unary_random("sin", dm.det_sin, ang_ranges, Rng(0x51AD0001), N_RANDOM)
    t.unary_random("cos", dm.det_cos, ang_ranges, Rng(0x51AD0002), N_RANDOM)

    # --- tan : coordinated-turn bank domain, away from the +/-pi/2 poles (|phi| < ~83 deg) ---
    tan_lim = 1.45
    tan_ranges = [(-tan_lim, 0.0), (0.0, tan_lim)]
    tan_bounds = [0.0, PI / 4, -PI / 4, 1.0, -1.0, tan_lim, -tan_lim,
                  1e-12, -1e-12, 2.0 ** -27]
    t.unary_many("tan", dm.det_tan, tan_bounds)
    t.unary_random("tan", dm.det_tan, tan_ranges, Rng(0x7A4D0003), N_RANDOM)

    # --- atan : full real line; hit every fdlibm reduction-region boundary ---
    atan_edges = [0.4375, 0.6875, 1.1875, 2.4375]              # 7/16, 11/16, 19/16, 39/16
    atan_bounds = [0.0, 2.0 ** -27, 2.0 ** -27 * 1.0001, -(2.0 ** -27), 2.0 ** -28,
                   1.0, -1.0, 0.5, -0.5, 1.5, 2.0, 1e3, 1e6, -1e6, 2.0 ** 65]
    for e in atan_edges:
        atan_bounds += [e, e - 1e-9, e + 1e-9, -e, -e - 1e-9, -e + 1e-9]
    t.unary_many("atan", dm.det_atan, atan_bounds)
    # cover small/mid/large magnitudes, both signs (well within the 2^66 cutoff)
    atan_ranges = [(-1.0, 1.0), (-3.0, 3.0), (-50.0, 50.0), (-5e3, 5e3), (1.0, 1e6)]
    t.unary_random("atan", dm.det_atan, atan_ranges, Rng(0xA7A40004), N_RANDOM)

    # --- atan2(y, x) : great-circle longitude step; all sign quadrants + the axis cases ---
    atan2_bounds = [(0.0, 0.0), (1.0, 0.0), (-1.0, 0.0), (0.0, 1.0), (0.0, -1.0),
                    (1.0, 1.0), (1.0, -1.0), (-1.0, 1.0), (-1.0, -1.0),
                    (0.5, 2.0), (-0.5, 2.0), (0.5, -2.0), (-0.5, -2.0),
                    (1e-9, 1.0), (1e-9, -1.0), (-1e-9, 1.0), (-1e-9, -1.0)]
    for y, x in atan2_bounds:
        t.binary("atan2", dm.det_atan2, y, x)
    rng = Rng(0xA7A20005)
    for i in range(N_RANDOM):
        # magnitudes spanning the unit-vector components a great-circle step produces
        y = rng.uniform(-2.0, 2.0)
        x = rng.uniform(-2.0, 2.0)
        t.binary("atan2", dm.det_atan2, y, x)

    # --- asin : [-1, 1] incl. the +/-1 clamp and near-edge values ---
    asin_bounds = [0.0, 1.0, -1.0, 0.9999999, -0.9999999, 0.999999, -0.999999,
                   0.5, -0.5, 0.25, -0.25, 0.7071067811865476, -0.7071067811865476,
                   2.0 ** -27, -(2.0 ** -27)]
    t.unary_many("asin", dm.det_asin, asin_bounds)
    t.unary_random("asin", dm.det_asin, [(-1.0, 1.0), (-0.5, 0.5), (0.9, 1.0), (-1.0, -0.9)],
                   Rng(0xA5170006), N_RANDOM)

    # --- sqrt : SEADS lengths/areas; incl. 0, tiny, perfect squares, R^2 ~ 2.25e8 ---
    sqrt_bounds = [0.0, 1e-12, 1.0, 2.0, 3.0, 4.0, 9.0, 16.0, 100.0, 15000.0,
                   15000.0 ** 2, 1e6, 1e8]
    t.unary_many("sqrt", dm.det_sqrt, sqrt_bounds)
    t.unary_random("sqrt", dm.det_sqrt,
                   [(1e-12, 4.0), (1.0, 1e4), (1e4, 1e8), (0.0, 1.0)],
                   Rng(0x5027007), N_RANDOM)

    # --- wrap_pi : normalize to (-pi, pi]; exercise the just-over-pi nudge + many periods ---
    wrap_bounds = [0.0, PI, -PI, TWO_PI, -TWO_PI, 3 * PI, -3 * PI, 4 * PI, -4 * PI,
                   PI + 1e-9, PI - 1e-9, -PI + 1e-9, -PI - 1e-9, 100.0, -100.0]
    for k in range(-3, 4):
        c = k * TWO_PI
        wrap_bounds += [c, c + 1e-6, c - 1e-6]
    wrap_ranges = [(-6 * PI, -2 * PI), (-2 * PI, 2 * PI), (2 * PI, 6 * PI)]
    t.unary_many("wrap_pi", dm.wrap_pi, wrap_bounds)
    t.unary_random("wrap_pi", dm.wrap_pi, wrap_ranges, Rng(0x37A90008), N_RANDOM)

    # --- wrap_2pi : normalize to [0, 2pi); exercise both wrap edges + many periods ---
    wrap2_bounds = [0.0, 1e-9, -1e-9, TWO_PI, -TWO_PI, TWO_PI - 1e-9, TWO_PI + 1e-9,
                    PI, -PI, 100.0, -100.0]
    for k in range(-3, 4):
        c = k * TWO_PI
        wrap2_bounds += [c, c + 1e-6, c - 1e-6]
    t.unary_many("wrap_2pi", dm.wrap_2pi, wrap2_bounds)
    t.unary_random("wrap_2pi", dm.wrap_2pi, wrap_ranges, Rng(0x37A90009), N_RANDOM)

    return t.emit()


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    content = build()
    if args.check:
        cur = HEADER.read_text(encoding="utf-8") if HEADER.exists() else ""
        if cur != content:
            print("FAIL: detmath_vectors.h out of sync (run gen_detmath_vectors.py)")
            sys.exit(1)
        print("PASS: detmath_vectors.h in sync")
        return
    HEADER.parent.mkdir(parents=True, exist_ok=True)
    HEADER.write_text(content, encoding="utf-8")
    n = content.count('{ "')
    print(f"wrote {HEADER} ({n} vectors)")


if __name__ == "__main__":
    main()
