#!/usr/bin/env python3
"""
gen_framing_vectors.py — emit src/net/framing_vectors.h from the framing reference.

Cross-impl parity vectors for the length-prefixed stream framing (netcode layer 7). The C++ test
(src/net/framing_test_main.cpp) asserts, per batch:
  * ENCODE parity — C++ encode_frame over the payloads == these exact canonical stream bytes,
  * CHUNK-BOUNDARY INVARIANCE — feeding the stream through the StreamReassembler under EVERY listed
    chunking yields byte-identical frames (== the original payloads), and
  * PARTIAL-FRAME BUFFERED — a stream truncated mid-payload / mid-prefix emits no frame and buffers.

The payloads are whole protocol-6 snapshot frames (reused from snapshot_ref, incl. one large frame
that forces a multi-byte LEB128 length prefix). Everything is emitted as byte literals + integer
offsets, so the header is byte-reproducible on every platform and CI `--check` stays green.

Usage:  python tools/gen_framing_vectors.py [--check]
"""
import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import geo001_ref as g
import snapshot_ref as s
import framing_ref as fr

ROOT = Path(__file__).resolve().parent.parent
HEADER = ROOT / "src" / "net" / "framing_vectors.h"


def bytes_literal(b):
    return "{" + ",".join("0x%02x" % x for x in b) + "}"


def _payload_batches():
    """The framed payload batches. Reuses extreme snapshots from the snapshot reference; the big
    frame (8 aircraft + 60 rounds) forces a payload length >= 128 -> a multi-byte length prefix."""
    small = s.encode_snapshot(s.Snapshot(1, [s.from_kernel(1, 0.0, 0.0, 0.7853981633974483, 1000.0,
                                                           0.0, 250.0, 0.0, 150.0, 0.0, 340.0)]))
    big_ents = [s.from_kernel(i, (i * 7) % 90, (i * 13) % 180 - 90, (i * 11) % 360,
                             (i * 137) % 8000, (i * 17) % 80 - 40, (i * 29) % 320,
                             (i * 19) % 60 - 30, 100.0 + i, float(i % 5), 200.0 + 3 * i,
                             float((i % 4) - 1))
                for i in range(1, 9)]
    big_projs = [s.proj_from_kernel(j, 0.01 * j, 0.02 * j, 1.0, 1000.0 + j, 12.0, 200 - j, j % 8)
                 for j in range(60)]
    big = s.encode_snapshot(s.Snapshot(100000, big_ents, big_projs))
    return [
        ("empty", []),
        ("one_small", [small]),
        ("several_small", [small, small, small]),
        ("one_large", [big]),
        ("mixed", [small, big, small, big]),
    ]


def _frame_offsets(payloads):
    """Cumulative stream offset at the START of each frame (its length prefix)."""
    offs, pos = [], 0
    for p in payloads:
        offs.append(pos)
        pos += len(g.leb128_encode_u64(len(p))) + len(p)
    return offs


def _chunkings(stream, offs):
    """The fixed chunkings the C++ test replays. Each is a list of (offset, length) chunk spans
    partitioning the stream — emitted as spans so the header carries no duplicated bytes."""
    n = len(stream)

    def spans(cuts):
        cuts = sorted(set(cuts))
        return [(cuts[i], cuts[i + 1] - cuts[i]) for i in range(len(cuts) - 1)]

    out = []
    out.append(("whole", [(0, n)] if n else []))
    out.append(("one_byte", [(i, 1) for i in range(n)]))
    out.append(("every_3", [(i, min(3, n - i)) for i in range(0, n, 3)]))
    out.append(("on_boundary", spans([0] + offs + [n])))
    out.append(("into_prefix", spans([0] + [min(p + 1, n) for p in offs] + [n])))
    if n > 4:
        out.append(("giant_plus_sliver", [(0, n - 3), (n - 3, 3)]))
    return out


def build():
    batches = _payload_batches()

    L = ["// AUTO-GENERATED by tools/gen_framing_vectors.py — DO NOT EDIT.",
         "// Length-prefixed stream framing (netcode layer 7) parity vectors: C++ framing codec vs",
         "// tools/framing_ref.py. Canonical stream bytes + frame offsets/lengths + several fixed",
         "// chunkings; the C++ test asserts every chunking yields byte-identical frames.",
         "#pragma once",
         "#include <cstddef>",
         "namespace seads { namespace framing_vec {",
         "",
         "struct Span { int off; int len; };",
         "struct Chunking { const char* name; const Span* spans; int n_spans; };",
         "struct FrameSpan { int off; int len; };",
         "struct Batch { const char* name;",
         "               const unsigned char* stream; int stream_len;",
         "               const FrameSpan* frames; int n_frames;",
         "               const Chunking* chunkings; int n_chunkings; };",
         ""]

    batch_entries = []
    for idx, (name, payloads) in enumerate(batches):
        stream = fr.encode_stream(payloads)
        offs = _frame_offsets(payloads)

        # canonical stream bytes
        if stream:
            L.append(f"constexpr unsigned char B{idx}_STREAM[] = {bytes_literal(stream)};")
        else:
            L.append(f"constexpr unsigned char B{idx}_STREAM[] = {{0}};  // empty (len 0)")

        # frame spans (offset + length of each PAYLOAD within the stream)
        L.append(f"constexpr FrameSpan B{idx}_FRAMES[] = {{")
        for p, o in zip(payloads, offs):
            hdr = len(g.leb128_encode_u64(len(p)))
            L.append(f"  {{ {o + hdr}, {len(p)} }},")
        if not payloads:
            L.append("  { 0, 0 },  // (unused; n_frames = 0)")
        L.append("};")

        # chunkings
        chs = _chunkings(stream, offs)
        for ci, (cname, spans) in enumerate(chs):
            L.append(f"constexpr Span B{idx}_CH{ci}_SPANS[] = {{")
            for (o, ln) in spans:
                L.append(f"  {{ {o}, {ln} }},")
            if not spans:
                L.append("  { 0, 0 },  // (unused; n_spans = 0)")
            L.append("};")
        L.append(f"constexpr Chunking B{idx}_CHUNKINGS[] = {{")
        for ci, (cname, spans) in enumerate(chs):
            L.append(f'  {{ "{cname}", B{idx}_CH{ci}_SPANS, {len(spans)} }},')
        L.append("};")
        L.append("")

        stream_len = len(stream)
        batch_entries.append(
            f'  {{ "{name}", B{idx}_STREAM, {stream_len}, B{idx}_FRAMES, {len(payloads)}, '
            f"B{idx}_CHUNKINGS, {len(chs)} }},")

    L.append("constexpr Batch BATCHES[] = {")
    L += batch_entries
    L += ["};",
          "constexpr int BATCH_COUNT = sizeof(BATCHES)/sizeof(BATCHES[0]);",
          "",
          "}} // namespace seads::framing_vec"]
    return "\n".join(L) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="fail if header is out of sync")
    args = ap.parse_args()
    content = build()
    if args.check:
        cur = HEADER.read_text(encoding="utf-8") if HEADER.exists() else ""
        if cur != content:
            print("FAIL: framing_vectors.h out of sync (run gen_framing_vectors.py)")
            sys.exit(1)
        print("PASS: framing_vectors.h in sync")
        return
    HEADER.parent.mkdir(parents=True, exist_ok=True)
    HEADER.write_text(content, encoding="utf-8")
    print(f"wrote {HEADER}")


if __name__ == "__main__":
    main()
