#!/usr/bin/env python3
"""
gen_envelope_tables.py — emit src/kernel/envelope_tables.h from the tuning envelopes.

Emits, for EVERY roster tuning envelope in data/tuning/envelopes/*.json, the radian-unit
LUTs (phi_max, roll_rate in rad / rad-per-s; climb_max/min in m/s) as exact hex-float arrays so
the C++ kernel interpolates BIT-IDENTICAL tables to tools/ref_kernel.py. The deg->rad conversion
is baked into the nodes by tools/envelopes.load_envelope (single source of truth). CI checks sync
with --check. (Pre-mesh-variants this emitted only scenario-referenced envelopes, which left
Yak-3/La-7 without envtab entries; the full roster is emitted now so every airframe can fly in a
recording. Every scenario-referenced envelope must still exist — asserted below.)

Usage:  python tools/gen_envelope_tables.py [--check]
"""
import argparse, json, sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import envelopes as envmod

ROOT = Path(__file__).resolve().parent.parent
HEADER = ROOT / "src" / "kernel" / "envelope_tables.h"
SCEN_DIR = ROOT / "config" / "scenarios"


def cpp_name(env):
    return "".join(c.upper() if c.isalnum() else "_" for c in env)


def roster_envelopes():
    """All tuning envelope basenames, sorted for stable output. Sanity: every envelope any
    scenario references must be one of them (a scenario can't name a missing tuning file)."""
    names = sorted(p.stem for p in envmod.ENV_DIR.glob("*.json"))
    referenced = set()
    for p in sorted(SCEN_DIR.glob("*.json")):
        doc = json.loads(p.read_text(encoding="utf-8"))
        for ac in doc["aircraft"]:
            referenced.add(ac["envelope"])
    missing = referenced - set(names)
    assert not missing, f"scenario references envelopes with no tuning JSON: {sorted(missing)}"
    return names


def hx(v):
    return float.hex(float(v))


def _lut(field, env):
    xs, ys = env[field]
    assert len(xs) == 5 and len(ys) == 5, f"{field}: expected 5-point LUT, got {len(xs)}"
    sx = ", ".join(hx(v) for v in xs)
    sy = ", ".join(hx(v) for v in ys)
    return f"  /*{field}*/ {{{{{sx}}}, {{{sy}}}}}"


def build():
    L = [
        "// AUTO-GENERATED by tools/gen_envelope_tables.py from data/tuning/envelopes/ — DO NOT EDIT.",
        "// Radian-unit LUTs (deg->rad baked into nodes) shared bit-for-bit with tools/ref_kernel.py.",
        "#pragma once",
        '#include "flight_types.h"',
        "namespace seads { namespace envtab {",
    ]
    for name in roster_envelopes():
        env = envmod.load_envelope(name)
        L.append(f"constexpr Envelope {cpp_name(name)} = {{")
        L.append(",\n".join(_lut(f, env) for f in envmod.LUT_FIELDS) + ",")
        scal = ", ".join(hx(env[f]) for f in envmod.AERO_FIELDS)
        L.append(f"  /*{'/'.join(envmod.AERO_FIELDS)}*/ {scal}")
        L.append("};")
    L.append("}} // namespace seads::envtab")
    return "\n".join(L) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="fail if header is out of sync")
    args = ap.parse_args()
    content = build()
    if args.check:
        cur = HEADER.read_text(encoding="utf-8") if HEADER.exists() else ""
        if cur != content:
            print("FAIL: envelope_tables.h out of sync (run gen_envelope_tables.py)")
            sys.exit(1)
        print("PASS: envelope_tables.h in sync")
        return
    HEADER.parent.mkdir(parents=True, exist_ok=True)
    HEADER.write_text(content, encoding="utf-8")
    print(f"wrote {HEADER}")


if __name__ == "__main__":
    main()
